import { researchTiers, type ResearchTier } from "../../config/researchTiers.ts";

export type EconomicLot={id:string;kind:"PROMOTIONAL"|"PURCHASED"|"ADJUSTMENT";available:number;reserved:number;expiresAt:string|null};
export function spendOrder(lots:EconomicLot[],now=new Date()){return lots.filter((lot)=>lot.available>0&&(lot.kind!=="PROMOTIONAL"||Boolean(lot.expiresAt&&new Date(lot.expiresAt)>now))).sort((a,b)=>{const kind=(value:EconomicLot["kind"])=>value==="PROMOTIONAL"?0:value==="PURCHASED"?1:2;const delta=kind(a.kind)-kind(b.kind);if(delta)return delta;if(a.kind==="PROMOTIONAL"&&b.kind==="PROMOTIONAL")return new Date(a.expiresAt!).getTime()-new Date(b.expiresAt!).getTime();return a.id.localeCompare(b.id);});}
export function allocateTokens(lots:EconomicLot[],required:number,now=new Date()){let remaining=required;const allocations=spendOrder(lots,now).flatMap((lot)=>{if(!remaining)return[];const tokens=Math.min(remaining,lot.available);remaining-=tokens;return[{lotId:lot.id,kind:lot.kind,tokens,expiresAt:lot.expiresAt}]});if(remaining)throw new Error("INSUFFICIENT_TOKENS");return allocations;}
export function tierTokens(tier:ResearchTier){return researchTiers[tier].tokens;}
export function costStatus(cost:number|null,tier:ResearchTier,unknown=false){if(unknown||cost===null)return"UNKNOWN_COST" as const;const config=researchTiers[tier];if(cost>=config.hardCogsUsd)return"LIMIT_REACHED" as const;if(cost>=config.hardCogsUsd*.9)return"NEAR_LIMIT" as const;if(cost>config.targetCogsUsd)return"WARNING" as const;return"HEALTHY" as const;}
export function circuitDecision(cost:number,projected:number,tier:ResearchTier,importance:"OPTIONAL"|"MATERIAL"|"ESSENTIAL"="OPTIONAL"){const hard=researchTiers[tier].hardCogsUsd;const ratio=cost/hard;if(cost+projected>hard)return{allowed:false,mode:"LIMIT_REACHED" as const};if(ratio>=.9&&importance!=="ESSENTIAL")return{allowed:false,mode:"ESSENTIAL_ONLY" as const};if(ratio>=.75&&importance==="OPTIONAL")return{allowed:false,mode:"REDUCE_OPTIONAL" as const};return{allowed:true,mode:ratio>=.9?"ESSENTIAL_ONLY" as const:ratio>=.75?"REDUCE_OPTIONAL" as const:"NORMAL" as const};}
export function researchEconomics(input:{tier:ResearchTier;promo:number;purchased:number;cogs:number;usefulFindings:number}){const retail=researchTiers[input.tier].retailValueUsd;return{retailEquivalentUsd:retail,promotionalValueConsumedUsd:input.promo,paidTokenValueConsumedUsd:input.purchased,researchCogsUsd:input.cogs,contributionBeforePaymentFeesUsd:input.purchased-input.cogs,betaAcquisitionCostUsd:input.purchased===0?input.cogs:0,costPerUsefulFindingUsd:input.usefulFindings>0?input.cogs/input.usefulFindings:null};}
