import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { circuitDecision } from "./economics";
import type { ResearchTier } from "@/config/researchTiers";

export type TokenBalance={organization_id:string;available_tokens:number;promotional_tokens:number;purchased_tokens:number;adjustment_tokens:number;reserved_tokens:number;next_promo_expiry:string|null};
export async function getTokenBalance(organizationId?:string){const supabase=await createClient();const{data,error}=await supabase.rpc("get_token_balance",{target_organization:organizationId||null});if(error)return null;return data as TokenBalance;}
export async function reserveResearch(input:{productId:string;tier:ResearchTier;idempotencyKey:string}){const supabase=await createClient();const{data,error}=await supabase.rpc("reserve_research_tokens",{target_product:input.productId,tier:input.tier,idempotency:input.idempotencyKey});if(error)throw new Error(error.message.includes("INSUFFICIENT_TOKENS")?"INSUFFICIENT_TOKENS":error.message);return data as {research_job_id:string;reservation_id:string;status:"RESERVED"|"SETTLED"|"REFUNDED";tokens:number;promotional_tokens:number;purchased_tokens:number;available_after:number;idempotent:boolean};}
export async function settleResearch(jobId:string,metrics:Record<string,number>){const admin=createAdminClient();const{data,error}=await admin.rpc("settle_research_tokens",{target_job:jobId,idempotency:`settle:${jobId}`,metrics});if(error)throw new Error(error.message);return data;}
export async function refundResearch(jobId:string,message:string){const admin=createAdminClient();const{data,error}=await admin.rpc("refund_research_tokens",{target_job:jobId,idempotency:`refund:${jobId}`,failure_message:message});if(error)throw new Error(error.message);return data;}
export async function markResearchRunning(jobId:string){const admin=createAdminClient();const{error}=await admin.from("research_jobs").update({status:"RUNNING",started_at:new Date().toISOString()}).eq("id",jobId).eq("status","RESERVED");if(error)throw new Error(error.message);}
export async function checkResearchCost(jobId:string,projectedCost:number,importance:"OPTIONAL"|"MATERIAL"|"ESSENTIAL"="OPTIONAL"){const admin=createAdminClient();const{data,error}=await admin.from("research_jobs").select("research_tier,accumulated_cogs_usd,has_unknown_cost").eq("id",jobId).single();if(error||!data)throw new Error("Research cost context is unavailable.");if(data.has_unknown_cost)return{allowed:false,mode:"UNKNOWN_COST" as const};return circuitDecision(Number(data.accumulated_cogs_usd||0),projectedCost,data.research_tier as ResearchTier,importance);}
export async function recordResearchCost(input:{jobId:string;provider:string;service:string;operation:string;costUsd:number|null;costType:"ACTUAL"|"ESTIMATED"|"UNKNOWN";category:"SEARCH"|"MODEL"|"EXTERNAL_API"|"RETRIEVAL"|"COMPUTE"|"OTHER";idempotencyKey:string;metadata?:Record<string,unknown>}){const admin=createAdminClient();const{data,error}=await admin.rpc("record_research_cost",{target_job:input.jobId,provider_name:input.provider,service_name:input.service,operation_name:input.operation,cost_value:input.costUsd,cost_kind:input.costType,category:input.category,idempotency:input.idempotencyKey,details:input.metadata||{}});if(error)throw new Error(error.message);return data;}
