import Link from "next/link";
import { PageHeader, Status, formatDate } from "@/components/china-desk-app/ui";
import { requireWorkspace } from "@/lib/china-desk/auth";
import { createClient } from "@/lib/supabase/server";
import { getTokenBalance } from "@/lib/tokens/service";
import { PaymentControls } from "@/components/china-desk-app/payment-controls";
import { paymentConfiguration } from "@/lib/payments/config";

const eventLabels:Record<string,string>={PROMO_GRANT:"Beta Tokens added",PURCHASE_GRANT:"Purchased Tokens added",RESEARCH_RESERVE:"Research reserved",RESEARCH_SETTLE:"Research completed",RESEARCH_REFUND:"Tokens returned",PROMO_EXPIRE:"Promotional Tokens expired",ADMIN_ADJUSTMENT:"Balance adjustment",REVERSAL:"Reversal"};

export default async function TokensPage({searchParams}:{searchParams:Promise<{payment?:string}>}){
  const context=await requireWorkspace();const organizationId=context.organization!.id;const supabase=await createClient();
  const [balance,ledgerResult,lotsResult,accountResult,refillResult,paymentsResult]=await Promise.all([
    getTokenBalance(),
    supabase.from("token_ledger").select("id,event_type,token_delta,reserved_delta,reason,created_at,research_job_id").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(100),
    supabase.from("token_lots").select("id,kind,available_tokens,reserved_tokens,expires_at,source_type").eq("organization_id",organizationId).order("created_at",{ascending:false}),
    supabase.from("billing_accounts").select("payment_profile_status,payment_method_brand,payment_method_last_four").eq("organization_id",organizationId).maybeSingle(),
    supabase.from("auto_refill_settings").select("enabled,trigger_tokens,refill_tokens,monthly_cap_usd,status").eq("organization_id",organizationId).maybeSingle(),
    supabase.from("payment_transactions").select("id,purchase_type,token_pack,total_minor,currency,status,receipt_url,created_at").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(50),
  ]);
  const ledger=ledgerResult.data||[],lots=lotsResult.data||[],payments=paymentsResult.data||[],config=paymentConfiguration(),params=await searchParams;
  return <><PageHeader eyebrow="ACCOUNT · TOKENS" title={`${balance?.available_tokens??0} Tokens available.`} description="One Meridian Token represents $1 of research value. Tokens are reserved when research begins and only settled when a usable result is completed." action={<Link href="/meridian/app/product" className="text-sm text-accent">Start research →</Link>}/>
    <section className="grid border-y border-line md:grid-cols-4">{[["AVAILABLE",balance?.available_tokens??0],["PROMOTIONAL",balance?.promotional_tokens??0],["PURCHASED",balance?.purchased_tokens??0],["RESERVED",balance?.reserved_tokens??0]].map(([label,value])=><div key={label} className="border-b border-line py-7 md:border-b-0 md:border-r md:px-6 md:first:pl-0 md:last:border-r-0"><p className="eyebrow text-stone">{label}</p><p className="mt-4 text-4xl font-medium tracking-[-0.06em]">{value}</p></div>)}</section>
    {balance?.next_promo_expiry?<p className="mt-6 text-sm text-charcoal">Promotional Tokens expire {formatDate(balance.next_promo_expiry)}. They are always used before purchased Tokens.</p>:null}
    {params.payment==="processing"?<p role="status" className="mt-8 border-y border-accent/30 py-4 text-sm text-accent">PAYMENT PROCESSING · We’re confirming your payment with Paddle. Tokens appear only after verified completion.</p>:null}
    <PaymentControls enabled={config.configured} profileStatus={accountResult.data?.payment_profile_status||"NOT_CONFIGURED"} balance={balance?.available_tokens??0} autoRefill={refillResult.data}/>
    {payments.length?<section className="mt-20"><div className="border-b border-line pb-5"><p className="eyebrow text-stone">PAYMENTS</p><h2 className="mt-3 text-3xl font-medium tracking-[-0.05em]">Payment history.</h2></div>{payments.map((payment)=><article key={payment.id} className="grid gap-3 border-b border-line py-5 sm:grid-cols-4 sm:items-center"><div><p className="font-medium">{payment.purchase_type==="PAYMENT_PROFILE"?"Payment Profile":`${payment.token_pack||0} Tokens`}</p><p className="mt-1 text-xs text-stone">{formatDate(payment.created_at)}</p></div><Status>{payment.status}</Status><p className="font-mono text-sm">{payment.total_minor!==null&&payment.currency?`${payment.currency} ${(Number(payment.total_minor)/100).toFixed(2)}`:"No charge"}</p><p className="sm:text-right">{payment.receipt_url?<a href={payment.receipt_url} target="_blank" rel="noreferrer" className="text-sm text-accent">Receipt ↗</a>:<span className="text-xs text-stone">Receipt in Paddle portal</span>}</p></article>)}</section>:null}
    <section className="mt-20"><div className="flex items-end justify-between border-b border-line pb-5"><div><p className="eyebrow text-stone">ACTIVITY</p><h2 className="mt-3 text-3xl font-medium tracking-[-0.05em]">Token history.</h2></div><span className="text-xs text-stone">Organization wallet</span></div>{ledger.length?ledger.map((entry)=><article key={entry.id} className="grid gap-3 border-b border-line py-6 md:grid-cols-12 md:items-center"><div className="md:col-span-5"><p className="font-medium">{eventLabels[entry.event_type]||entry.event_type}</p><p className="mt-1 text-xs text-stone">{entry.reason||"Meridian research activity"}</p></div><div className="md:col-span-2"><Status>{entry.event_type.replaceAll("_"," ")}</Status></div><p className={`font-mono text-sm md:col-span-2 ${entry.token_delta>0?"text-jade":entry.token_delta<0?"text-ink":"text-stone"}`}>{entry.token_delta>0?"+":""}{entry.token_delta} Tokens</p><p className="text-xs text-stone md:col-span-3 md:text-right">{formatDate(entry.created_at)}</p></article>):<div className="py-14"><p className="text-lg">No Token activity yet.</p><p className="mt-3 max-w-lg text-sm leading-6 text-charcoal">Your balance and research reservations will appear here when an administrator activates your beta allocation.</p></div>}</section>
    {lots.some((lot)=>lot.reserved_tokens>0)?<p className="mt-8 text-xs leading-5 text-stone">Reserved Tokens are protected while a research job is running. Technical failures return eligible Tokens automatically.</p>:null}
  </>;
}
