import type { ReactNode } from "react";

export function BubbleCard({children,className=""}:{children:ReactNode;className?:string}){return <section className={`bubble-card p-6 sm:p-8 ${className}`}>{children}</section>}
export function ScoreChip({score,label}:{score:number|null;label?:string}){return <div className="inline-flex flex-wrap items-end justify-end gap-2"><strong className="text-3xl font-medium tracking-[-0.06em] text-accent">{score??"—"}</strong><span className="pb-1 text-xs text-stone">/ 100</span>{label?<span className="rounded-full border border-accent/25 bg-accent/[0.08] px-2.5 py-1 font-mono text-[0.56rem] uppercase tracking-[0.1em] text-accent">{label}</span>:null}</div>}
export function ConfidenceChip({score,confidence}:{score:number|null;confidence?:string}){const high=(score??0)>=75;return <span className={`inline-flex rounded-full border px-2.5 py-1 font-mono text-[0.56rem] uppercase tracking-[0.09em] ${high?"border-jade/30 bg-jade/[0.08] text-jade":"border-amber/30 bg-amber/[0.08] text-amber"}`}>Evidence {score??"unscored"}{score!=null?"/100":""}{confidence?` · ${confidence}`:""}</span>}
export function AttentionCard({children,title,score,confidence,action}:{children:ReactNode;title:string;score:number|null;confidence:number|null;action:string}){return <BubbleCard className="attention-card"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-coral">WORTH YOUR ATTENTION</p><h3 className="mt-4 text-xl font-medium tracking-[-0.035em]">{title}</h3></div><ScoreChip score={score} label="Relevance"/></div><p className="mt-6 text-sm leading-6 text-ink">{children}</p><div className="mt-6"><ConfidenceChip score={confidence}/></div><p className="mt-6 border-t border-line pt-5 text-sm text-coral">{action}</p></BubbleCard>}

const workflow=["PRODUCT_PROFILE","QUERY_PLANNING","SEARCHING","FETCHING","EVIDENCE_REVIEW","SCORING","INTERPRETING","COMPLETE"] as const;
const labels:Record<string,string>={PRODUCT_PROFILE:"Product understood",QUERY_PLANNING:"Search strategy built",SEARCHING:"Searching relevant sources",FETCHING:"Reviewing source pages",EVIDENCE_REVIEW:"Reviewing evidence",SCORING:"Scoring findings",INTERPRETING:"Preparing results",COMPLETE:"Analysis ready"};
const narration:Record<string,string>={PRODUCT_PROFILE:"Understanding your product and China objective.",QUERY_PLANNING:"Building a China-specific research strategy.",SEARCHING:"Looking for relevant companies and market signals.",FETCHING:"Checking the source pages behind the strongest results.",EVIDENCE_REVIEW:"Separating supported facts from assumptions and unknowns.",SCORING:"Ranking findings against your stated China objective.",INTERPRETING:"Preparing concise findings and recommended actions.",COMPLETE:"Your current China findings are ready to review.",FAILED:"The completed work and any partial findings remain available."};
export function AnalysisProgress({stage,status,completedStages,error}:{stage:string;status:string;completedStages:string[];error?:string|null}){const reached=Math.max(0,workflow.indexOf(stage as typeof workflow[number]));const completeCount=status==="COMPLETE"?workflow.length:Math.max(completedStages.length,reached);const width=`${Math.round((completeCount/workflow.length)*100)}%`;return <section aria-live="polite" className="bubble-card p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className={`eyebrow ${status==="FAILED"?"text-signal-red":status==="COMPLETE"?"text-jade":"text-accent"}`}>{status==="FAILED"?"ANALYSIS PAUSED":status==="COMPLETE"?"ANALYSIS READY ✓":"MERIDIAN IS RESEARCHING YOUR CHINA MARKET"}</p><p className="mt-3 text-lg text-ink">{status==="FAILED"?`We couldn't complete ${labels[stage]?.toLowerCase()||"this stage"}.`:narration[stage]||labels[stage]||"Meridian is working."}</p></div><span className="font-mono text-[0.6rem] uppercase tracking-[0.1em] text-stone">{status}</span></div><div className="mt-7 h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><div className={`h-full rounded-full transition-[width] duration-700 ${status==="FAILED"?"bg-signal-red":status==="COMPLETE"?"bg-jade":"bg-accent"}`} style={{width}}/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{workflow.map((item,index)=><span key={item} className={`text-xs ${completedStages.includes(item)||index<reached?"text-jade":item===stage?"text-accent":"text-stone"}`}>{completedStages.includes(item)||index<reached?"✓ ":item===stage?"◉ ":"○ "}{labels[item]}</span>)}</div>{error?<><p className="mt-5 text-sm text-signal-red">{error}</p><p className="mt-2 text-sm text-charcoal">{narration.FAILED}</p></>:null}</section>}
