"use client";

import { AnimatePresence, motion } from "motion/react";
import { useActionState, useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { prepareProductUnderstanding, saveProductProfile, type ProductActionState, type UnderstandingState } from "@/app/desk/app/product/actions";
import { AnalysisProgress } from "./intelligence-ui";
import { researchTiers, type ResearchTier } from "@/config/researchTiers";

type InitialProfile={id?:string;company_url?:string|null;product_name?:string;product_description?:string|null;target_customer?:string|null;additional_context?:string|null;objectives?:string[];industry?:string;subindustry?:string|null;intended_use?:string|null;target_market_segment?:string|null;target_geography?:string;china_status?:string|null;keywords_en?:string[];keywords_zh?:string[];formal_terms_zh?:string[];procurement_terms_zh?:string[];regulatory_terms_zh?:string[];distributor_terms_zh?:string[];supplier_terms_zh?:string[];understanding_summary?:string|null;likely_audiences?:string[];understanding_mode?:string};
const saveInitial:ProductActionState={message:""};
const understandingInitial:UnderstandingState={message:""};
const goals=[['distributors','Find distributors'],['customers','Find customers'],['partners','Find partners'],['suppliers','Find suppliers'],['competitors','Understand competitors'],['tenders','Track tenders'],['pricing','Understand pricing'],['regulation','Understand regulation']] as const;
const steps=["Company","Product","Goal","Context","Understanding","Analyze"];
const inputClass="mt-4 w-full rounded-2xl border border-line-strong bg-elevated px-5 py-4 text-lg text-ink outline-none placeholder:text-stone/60 focus:border-accent/60";
const join=(value?:string[])=>value?.join("\n")||"";

export function ProductProfileWizard({initial,initialUrl="",tokenBalance=0}:{initial:InitialProfile|null;initialUrl?:string;tokenBalance?:number}){
  const router=useRouter();
  const [saveState,saveAction,saving]=useActionState(saveProductProfile,saveInitial);
  const formRef=useRef<HTMLFormElement>(null);const [understandingState,setUnderstandingState]=useState<UnderstandingState>(understandingInitial);const [understandingPending,startUnderstanding]=useTransition();
  const [step,setStep]=useState(0),[editing,setEditing]=useState(false),[confirmed,setConfirmed]=useState(false);
  const [url,setUrl]=useState(initial?.company_url||initialUrl),[description,setDescription]=useState(initial?.product_description||initial?.product_name||"");
  const [selectedGoals,setSelectedGoals]=useState<string[]>(initial?.objectives||[]),[audience,setAudience]=useState(initial?.target_customer||""),[context,setContext]=useState(initial?.additional_context||"");
  const [productName,setProductName]=useState(initial?.product_name||""),[summary,setSummary]=useState(initial?.understanding_summary||initial?.product_description||""),[likelyAudiences,setLikelyAudiences]=useState<string[]>(initial?.likely_audiences||[]),[industry,setIndustry]=useState(initial?.industry||"UNIVERSAL"),[understandingMode,setUnderstandingMode]=useState(initial?.understanding_mode||"USER_INPUT_FALLBACK");
  const [tier,setTier]=useState<ResearchTier>("STANDARD"),[requestId,setRequestId]=useState(()=>crypto.randomUUID());

  useEffect(()=>{if(saveState.success&&saveState.profileId){router.replace(`/meridian/app/product?id=${saveState.profileId}&research=complete&tokens=${saveState.tokensUsed||0}`);router.refresh();}},[router,saveState.profileId,saveState.success,saveState.tokensUsed]);
  useEffect(()=>{if(!saveState.message||saveState.success)return;const timer=window.setTimeout(()=>setRequestId(crypto.randomUUID()),0);return()=>window.clearTimeout(timer);},[saveState.message,saveState.success]);

  const toggle=(goal:string)=>setSelectedGoals((items)=>items.includes(goal)?items.filter((item)=>item!==goal):[...items,goal]);
  const canContinue=step===0?Boolean(url.trim()):step===1?Boolean(description.trim()):step===2?selectedGoals.length>0:true;
  const advance=()=>setStep((value)=>Math.min(5,value+1));
  const confirmUnderstanding=(wasEdited=false)=>{setUnderstandingMode(wasEdited?"USER_EDITED":understandingMode);setConfirmed(true);setEditing(false);setStep(5);};
  const buildUnderstanding=()=>startUnderstanding(async()=>{if(!formRef.current)return;const result=await prepareProductUnderstanding(understandingInitial,new FormData(formRef.current));setUnderstandingState(result);if(result.success){setProductName(result.productName||description);setSummary(result.summary||description);setLikelyAudiences(result.audiences||[]);setIndustry(result.industry||"UNIVERSAL");setUnderstandingMode(result.mode||"USER_INPUT_FALLBACK");setStep(4);setEditing(false);setConfirmed(false);}});

  const tierConfig=researchTiers[tier],canAfford=tokenBalance>=tierConfig.tokens;
  return <form ref={formRef} action={saveAction} className="max-w-5xl">
    <input type="hidden" name="research_tier" value={tier}/><input type="hidden" name="research_request_id" value={requestId}/>
    <input type="hidden" name="id" value={initial?.id||""}/><input type="hidden" name="company_url" value={url}/><input type="hidden" name="product_name" value={productName||description}/><input type="hidden" name="product_description" value={description}/><input type="hidden" name="understanding_summary" value={summary||description}/><input type="hidden" name="understanding_mode" value={understandingMode}/><input type="hidden" name="target_customer" value={audience}/><input type="hidden" name="additional_context" value={context}/>
    {selectedGoals.map((goal)=><input key={goal} type="hidden" name="objectives" value={goal}/>)}{likelyAudiences.map((item)=><input key={item} type="hidden" name="likely_audiences" value={item}/>)}

    <nav aria-label="Product setup progress" className="mb-10 grid grid-cols-6 gap-2">{steps.map((label,index)=><button key={label} type="button" onClick={()=>index<step&&setStep(index)} className={`min-h-12 border-t pt-3 text-left font-mono text-[0.55rem] uppercase tracking-[0.08em] ${index===step?"border-accent text-accent":index<step?"border-jade text-jade":"border-line text-stone"}`}><span className="block">0{index+1}</span><span className="mt-1 hidden md:block">{label}</span></button>)}</nav>

    <div className="bubble-card min-h-[27rem] p-6 sm:p-10"><AnimatePresence mode="wait"><motion.section key={step} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.35,ease:[.22,1,.36,1]}}>
      {step===0?<><p className="eyebrow text-accent">STEP 1 · YOUR COMPANY</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">Where can Meridian understand your product?</h2><label className="mt-10 block"><span className="text-sm font-medium text-ink">Company or product URL</span><input value={url} onChange={(event)=>setUrl(event.target.value.slice(0,500))} className={inputClass} inputMode="url" autoComplete="url" autoFocus placeholder="https://yourcompany.com/product"/></label><p className="mt-4 text-sm leading-6 text-charcoal">Meridian uses the public page as context. Your own description remains authoritative.</p></>:null}
      {step===1?<><p className="eyebrow text-accent">STEP 2 · WHAT DO YOU SELL?</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">Describe it in plain language.</h2><label className="mt-10 block"><span className="sr-only">What do you sell?</span><textarea value={description} onChange={(event)=>setDescription(event.target.value.slice(0,1000))} rows={5} className={inputClass} autoFocus placeholder="What the product does, who uses it, and the problem it solves"/></label></>:null}
      {step===2?<><p className="eyebrow text-accent">STEP 3 · YOUR CHINA GOAL</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">What should Meridian investigate?</h2><div className="mt-10 grid gap-3 sm:grid-cols-2">{goals.map(([goal,label])=><label key={goal} className={`flex min-h-16 cursor-pointer items-center justify-between rounded-2xl border px-5 py-4 text-sm transition-colors ${selectedGoals.includes(goal)?"border-accent/50 bg-accent/[0.1] text-ink":"border-line bg-white/[0.02] text-charcoal hover:border-line-strong"}`}><span>{label}</span><input type="checkbox" className="sr-only" checked={selectedGoals.includes(goal)} onChange={()=>toggle(goal)}/><span aria-hidden="true" className={`h-2.5 w-2.5 rounded-full ${selectedGoals.includes(goal)?"bg-accent":"bg-stone/40"}`}/></label>)}</div></>:null}
      {step===3?<><p className="eyebrow text-accent">STEP 4 · OPTIONAL CONTEXT</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">What would sharpen the search?</h2><div className="mt-10 grid gap-7 sm:grid-cols-2"><label><span className="text-sm font-medium text-ink">Target audience</span><textarea value={audience} onChange={(event)=>setAudience(event.target.value.slice(0,1000))} rows={4} className={inputClass} placeholder="Who buys, specifies, distributes or uses it?"/></label><label><span className="text-sm font-medium text-ink">Additional context</span><textarea value={context} onChange={(event)=>setContext(event.target.value.slice(0,2000))} rows={4} className={inputClass} placeholder="Constraints, regions or questions Meridian should know"/></label></div></>:null}
      {step===4?<><p className="eyebrow text-jade">MERIDIAN UNDERSTANDING</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">Does this look right?</h2><p className="mt-5 max-w-2xl text-sm leading-6 text-charcoal">{understandingState.message}</p>{editing?<div className="mt-8 space-y-6"><label className="block"><span className="eyebrow text-stone">PRODUCT / CATEGORY</span><input value={productName} onChange={(event)=>setProductName(event.target.value.slice(0,240))} className={inputClass}/></label><label className="block"><span className="eyebrow text-stone">WHAT IT DOES</span><textarea value={summary} onChange={(event)=>setSummary(event.target.value.slice(0,2000))} rows={4} className={inputClass}/></label><label className="block"><span className="eyebrow text-stone">LIKELY CHINA AUDIENCES</span><input value={likelyAudiences.join(", ")} onChange={(event)=>setLikelyAudiences(event.target.value.split(/[,，]/).map((item)=>item.trim()).filter(Boolean).slice(0,8))} className={inputClass}/></label><label className="block"><span className="eyebrow text-stone">INDUSTRY</span><select value={industry} onChange={(event)=>setIndustry(event.target.value)} className={inputClass}>{["UNIVERSAL","CONSUMER","INDUSTRIAL","TECHNOLOGY","MEDTECH"].map((item)=><option key={item}>{item}</option>)}</select></label><fieldset><legend className="eyebrow text-stone">CHINA OBJECTIVES</legend><div className="mt-4 grid gap-3 sm:grid-cols-2">{goals.map(([goal,label])=><label key={goal} className="flex min-h-12 cursor-pointer items-center gap-3 border-b border-line py-3 text-sm"><input type="checkbox" checked={selectedGoals.includes(goal)} onChange={()=>toggle(goal)}/>{label}</label>)}</div></fieldset></div>:<div className="mt-8 rounded-2xl border border-jade/25 bg-jade/[0.06] p-6"><p className="text-2xl font-medium tracking-[-0.04em]">{productName}</p><p className="mt-4 text-base leading-7 text-charcoal">{summary}</p><div className="mt-6 flex flex-wrap gap-2">{likelyAudiences.map((item)=><span key={item} className="rounded-full border border-line-strong px-3 py-2 text-xs text-ink">{item}</span>)}</div><p className="mt-6 text-xs text-stone">{industry} · {selectedGoals.map((goal)=>goals.find(([value])=>value===goal)?.[1]).filter(Boolean).join(" · ")}</p></div>}</>:null}
      {step===5?<><p className="eyebrow text-jade">UNDERSTANDING CONFIRMED ✓</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">Choose your research depth.</h2><div className="mt-9 grid gap-3 sm:grid-cols-2">{Object.values(researchTiers).map((item)=><button key={item.key} type="button" onClick={()=>setTier(item.key)} className={`min-h-32 rounded-2xl border p-5 text-left transition-colors ${tier===item.key?"border-accent bg-accent/[0.09]":"border-line bg-white/[0.02] hover:border-line-strong"}`}><span className="flex items-center justify-between gap-3"><strong className="text-sm font-medium">{item.name}</strong><span className="font-mono text-xs text-accent">{item.tokens} Tokens</span></span>{"recommended" in item?<span className="mt-3 block font-mono text-[0.55rem] uppercase tracking-[0.1em] text-jade">Recommended</span>:null}<span className="mt-3 block text-xs leading-5 text-charcoal">{item.description}</span></button>)}</div><div className="mt-8 grid grid-cols-3 gap-4 border-y border-line py-6"><div><p className="eyebrow text-stone">BALANCE</p><p className="mt-2 text-xl">{tokenBalance}</p></div><div><p className="eyebrow text-stone">RESEARCH COST</p><p className="mt-2 text-xl">{tierConfig.tokens}</p></div><div><p className="eyebrow text-stone">AFTER STARTING</p><p className={`mt-2 text-xl ${canAfford?"text-jade":"text-signal-red"}`}>{Math.max(0,tokenBalance-tierConfig.tokens)}</p></div></div>{!canAfford?<div className="mt-6 rounded-xl border border-amber/35 bg-amber/[0.07] p-5"><p className="eyebrow text-amber">MORE TOKENS REQUIRED</p><p className="mt-3 text-sm leading-6 text-ink">{tierConfig.name} requires {tierConfig.tokens} Tokens. Your available balance is {tokenBalance} Tokens.</p></div>:null}</>:null}
    </motion.section></AnimatePresence></div>

    <footer className="mt-6 flex items-center justify-between gap-5"><button type="button" disabled={step===0||saving||understandingPending} onClick={()=>setStep((value)=>Math.max(0,value-1))} className="min-h-12 text-sm text-charcoal disabled:opacity-0">← Back</button>
      {step<3?<button type="button" disabled={!canContinue} onClick={advance} className="min-h-12 rounded-xl bg-accent px-6 text-sm font-semibold text-[#071018] disabled:cursor-not-allowed disabled:opacity-35">Continue →</button>:null}
      {step===3?<button type="button" onClick={buildUnderstanding} disabled={understandingPending} className="min-h-12 rounded-xl bg-accent px-6 text-sm font-semibold text-[#071018] disabled:opacity-50">{understandingPending?"Understanding your product…":"Build Meridian understanding →"}</button>:null}
      {step===4&&!editing?<div className="flex flex-wrap justify-end gap-4"><button type="button" onClick={()=>setEditing(true)} className="min-h-12 text-sm text-charcoal">Edit understanding</button><button type="button" onClick={()=>confirmUnderstanding(false)} className="min-h-12 rounded-xl bg-jade px-6 text-sm font-semibold text-[#071018]">Looks right ✓</button></div>:null}
      {step===4&&editing?<button type="button" disabled={!productName||!summary} onClick={()=>confirmUnderstanding(true)} className="min-h-12 rounded-xl bg-jade px-6 text-sm font-semibold text-[#071018] disabled:opacity-40">Save understanding ✓</button>:null}
      {step===5?<button type="submit" disabled={saving||!confirmed||!canAfford} className="min-h-12 rounded-xl bg-accent px-6 text-sm font-semibold text-[#071018] disabled:opacity-40">{saving?`Reserving ${tierConfig.tokens} Tokens…`:`Run ${tierConfig.name} · ${tierConfig.tokens} Tokens →`}</button>:null}
    </footer>

    {understandingState.message&&!understandingState.success?<p role="alert" className="mt-6 rounded-xl border border-signal-red/30 bg-signal-red/[0.07] p-4 text-sm text-ink">{understandingState.message}</p>:null}
    {saving?<div className="mt-8"><p className="mb-4 rounded-xl border border-jade/30 bg-jade/[0.07] p-4 text-sm text-jade">{tierConfig.tokens} Tokens reserved ✓ · Research starting…</p><AnalysisProgress stage="QUERY_PLANNING" status="RUNNING" completedStages={["PRODUCT_PROFILE"]}/></div>:null}
    {saveState.message?<div className={`mt-8 rounded-2xl border p-5 ${saveState.success?"border-jade/35 bg-jade/[0.07]":"border-signal-red/35 bg-signal-red/[0.07]"}`} role={saveState.success?"status":"alert"}><p className={`eyebrow ${saveState.success?"text-jade":"text-signal-red"}`}>{saveState.success?"PROFILE SAVED ✓":"ANALYSIS PAUSED"}</p><p className="mt-3 text-sm text-ink">{saveState.message}</p>{saveState.success?<p className="mt-2 text-sm text-charcoal">SEARCH STRATEGY READY · {saveState.preparedSearches||0} research paths prepared</p>:null}</div>:null}

    <details className="mt-12 border-t border-line pt-7"><summary className="cursor-pointer text-sm text-charcoal">Advanced product details</summary><div className="mt-8 grid gap-6 sm:grid-cols-2"><label><span className="eyebrow text-stone">Industry</span><select name="industry" value={industry} onChange={(event)=>setIndustry(event.target.value)} className="mt-3 w-full">{["UNIVERSAL","CONSUMER","INDUSTRIAL","TECHNOLOGY","MEDTECH"].map((item)=><option key={item}>{item}</option>)}</select></label>{[["Subindustry","subindustry",initial?.subindustry||""],["Intended use","intended_use",initial?.intended_use||""],["Market segment","target_market_segment",initial?.target_market_segment||""],["Target geography","target_geography",initial?.target_geography||"China"],["Current China status","china_status",initial?.china_status||""]].map(([label,name,value])=><label key={name}><span className="eyebrow text-stone">{label}</span><input name={name} defaultValue={value} className="mt-3 w-full"/></label>)}{[["English terms","keywords_en",join(initial?.keywords_en)],["Chinese terminology","keywords_zh",join(initial?.keywords_zh)],["Formal terminology","formal_terms_zh",join(initial?.formal_terms_zh)],["Distributor terminology","distributor_terms_zh",join(initial?.distributor_terms_zh)],["Supplier terminology","supplier_terms_zh",join(initial?.supplier_terms_zh)],["Procurement terminology","procurement_terms_zh",join(initial?.procurement_terms_zh)],["Regulatory terminology","regulatory_terms_zh",join(initial?.regulatory_terms_zh)]].map(([label,name,value])=><label key={name}><span className="eyebrow text-stone">{label}</span><textarea name={name} defaultValue={value} rows={3} className="mt-3 w-full"/></label>)}</div></details>
  </form>;
}
