"use client";

import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { saveProductProfile, type ProductActionState } from "@/app/desk/app/product/actions";
import { AnalysisProgress } from "./intelligence-ui";

type InitialProfile={id?:string;company_url?:string|null;product_name?:string;company_name?:string|null;product_description?:string|null;target_customer?:string|null;additional_context?:string|null;objectives?:string[];industry?:string;subindustry?:string|null;intended_use?:string|null;target_market_segment?:string|null;target_geography?:string;china_status?:string|null;keywords_en?:string[];keywords_zh?:string[];formal_terms_zh?:string[];procurement_terms_zh?:string[];regulatory_terms_zh?:string[];distributor_terms_zh?:string[]};
const initialState:ProductActionState={message:""};
const goals=[['distributors','Find distributors'],['customers','Find customers'],['partners','Find partners'],['suppliers','Find suppliers'],['competitors','Understand competitors'],['tenders','Track tenders'],['pricing','Understand pricing'],['regulation','Understand regulation']] as const;
const steps=["Source","Product","Goal","Context","Analyze"];
const inputClass="mt-4 w-full rounded-2xl border border-line-strong bg-elevated px-5 py-4 text-lg text-ink outline-none placeholder:text-stone focus:border-accent/60";
const join=(value?:string[])=>value?.join("\n")||"";

export function ProductProfileWizard({initial}:{initial:InitialProfile|null}){const router=useRouter();const [state,action,pending]=useActionState(saveProductProfile,initialState);const [step,setStep]=useState(0);const [url,setUrl]=useState(initial?.company_url||"");const [product,setProduct]=useState(initial?.product_name||"");const [selectedGoals,setSelectedGoals]=useState<string[]>(initial?.objectives||[]);const [audience,setAudience]=useState(initial?.target_customer||"");const [context,setContext]=useState(initial?.additional_context||"");
  useEffect(()=>{if(state.success&&state.profileId){router.replace(`/meridian/app/product?id=${state.profileId}`);router.refresh();}},[router,state.profileId,state.success]);
  const canContinue=step===0?Boolean(url.trim()):step===1?Boolean(product.trim()):step===2?selectedGoals.length>0:true;
  const toggle=(goal:string)=>setSelectedGoals((items)=>items.includes(goal)?items.filter((item)=>item!==goal):[...items,goal]);
  return <form action={action} className="max-w-5xl"><input type="hidden" name="id" value={initial?.id||""}/><input type="hidden" name="company_url" value={url}/><input type="hidden" name="product_name" value={product}/><input type="hidden" name="product_description" value={product}/>{selectedGoals.map((goal)=><input key={goal} type="hidden" name="objectives" value={goal}/>)}<input type="hidden" name="target_customer" value={audience}/><input type="hidden" name="additional_context" value={context}/>
    <nav aria-label="Product setup progress" className="mb-10 grid grid-cols-5 gap-2">{steps.map((label,index)=><button key={label} type="button" onClick={()=>index<=step&&setStep(index)} className={`border-t pt-3 text-left font-mono text-[0.58rem] uppercase tracking-[0.1em] ${index===step?"border-accent text-accent":index<step?"border-jade text-jade":"border-line text-stone"}`}><span className="block">0{index+1}</span><span className="mt-1 hidden sm:block">{label}</span></button>)}</nav>
    <div className="bubble-card min-h-[25rem] p-6 sm:p-10">
      {step===0?<section><p className="eyebrow text-accent">STEP 1 · PRODUCT SOURCE</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">Where can Meridian understand your product?</h2><label className="mt-10 block"><span className="text-sm font-medium text-charcoal">Company or product URL</span><input value={url} onChange={(event)=>setUrl(event.target.value.slice(0,500))} className={inputClass} inputMode="url" autoComplete="url" autoFocus placeholder="https://yourcompany.com/product"/></label><p className="mt-4 text-sm leading-6 text-charcoal">Meridian reads only the public page you provide.</p></section>:null}
      {step===1?<section><p className="eyebrow text-accent">STEP 2 · PRODUCT</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">What do you sell?</h2><label className="mt-10 block"><span className="sr-only">What do you sell?</span><textarea value={product} onChange={(event)=>setProduct(event.target.value.slice(0,240))} rows={4} className={inputClass} autoFocus placeholder="Describe the product or service in plain language"/></label></section>:null}
      {step===2?<section><p className="eyebrow text-accent">STEP 3 · CHINA OBJECTIVE</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">What do you want to understand in China?</h2><div className="mt-10 grid gap-3 sm:grid-cols-2">{goals.map(([goal,label])=><label key={goal} className={`flex min-h-16 cursor-pointer items-center justify-between rounded-2xl border px-5 py-4 text-sm transition-colors ${selectedGoals.includes(goal)?"border-accent/50 bg-accent/[0.1] text-ink":"border-line bg-white/[0.02] text-charcoal hover:border-line-strong"}`}><span>{label}</span><input type="checkbox" className="sr-only" checked={selectedGoals.includes(goal)} onChange={()=>toggle(goal)}/><span aria-hidden="true" className={`h-2.5 w-2.5 rounded-full ${selectedGoals.includes(goal)?"bg-accent":"bg-stone/40"}`}/></label>)}</div></section>:null}
      {step===3?<section><p className="eyebrow text-accent">STEP 4 · CONTEXT</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">A little context helps Meridian prioritize.</h2><div className="mt-10 grid gap-7 sm:grid-cols-2"><label><span className="text-sm font-medium text-charcoal">Target audience · optional</span><textarea value={audience} onChange={(event)=>setAudience(event.target.value.slice(0,1000))} rows={4} className={inputClass} placeholder="Who buys, specifies, distributes or uses it?"/></label><label><span className="text-sm font-medium text-charcoal">Additional context · optional</span><textarea value={context} onChange={(event)=>setContext(event.target.value.slice(0,2000))} rows={4} className={inputClass} placeholder="Markets, constraints or questions Meridian should know"/></label></div></section>:null}
      {step===4?<section><p className="eyebrow text-accent">STEP 5 · ANALYZE</p><h2 className="mt-6 text-[clamp(2.4rem,6vw,5rem)] font-medium leading-[0.92] tracking-[-0.06em]">Ready to map your China opportunity.</h2><div className="mt-10 border-y border-line py-7 text-sm leading-6 text-charcoal"><p className="font-medium text-ink">{product}</p><p className="mt-3">{url}</p><p className="mt-3 text-stone">{selectedGoals.map((goal)=>goals.find(([value])=>value===goal)?.[1]).filter(Boolean).join(" · ")}</p>{audience?<p className="mt-5"><span className="text-stone">Audience:</span> {audience}</p>:null}{context?<p className="mt-3"><span className="text-stone">Context:</span> {context}</p>:null}</div></section>:null}
    </div>
    <footer className="mt-6 flex items-center justify-between"><button type="button" disabled={step===0||pending} onClick={()=>setStep((value)=>Math.max(0,value-1))} className="min-h-12 text-sm text-charcoal disabled:opacity-0">← Back</button>{step<4?<button type="button" disabled={!canContinue} onClick={()=>setStep((value)=>Math.min(4,value+1))} className="min-h-12 rounded-xl bg-accent px-6 text-sm font-semibold text-[#071018] disabled:cursor-not-allowed disabled:opacity-35">Continue →</button>:<button type="submit" disabled={pending||!product||!url||!selectedGoals.length} className="min-h-12 rounded-xl bg-accent px-6 text-sm font-semibold text-[#071018] disabled:cursor-not-allowed disabled:opacity-35">{pending?"Searching China…":"Analyze my China opportunity →"}</button>}</footer>
    {pending?<div className="mt-8"><AnalysisProgress stage="QUERY_PLANNING" status="RUNNING" completedStages={["PRODUCT_PROFILE"]}/></div>:null}
    {state.message?<div className={`mt-8 rounded-2xl border p-5 ${state.success?"border-jade/35 bg-jade/[0.07]":"border-signal-red/35 bg-signal-red/[0.07]"}`} role={state.success?"status":"alert"}><p className={`eyebrow ${state.success?"text-jade":"text-signal-red"}`}>{state.success?"PROFILE SAVED ✓":"ANALYSIS PAUSED"}</p><p className="mt-3 text-sm text-ink">{state.message}</p>{state.success?<p className="mt-2 text-sm text-charcoal">SEARCH STRATEGY READY · {state.preparedSearches||0} search paths prepared{state.searchStarted?" · highest-priority searches completed":""}</p>:null}</div>:null}
    <details className="mt-12 border-t border-line pt-7"><summary className="cursor-pointer text-sm text-charcoal">Advanced product details</summary><div className="mt-8 grid gap-6 sm:grid-cols-2">{[["Industry","industry",initial?.industry||""],["Subindustry","subindustry",initial?.subindustry||""],["Intended use","intended_use",initial?.intended_use||""],["Market segment","target_market_segment",initial?.target_market_segment||""],["Target geography","target_geography",initial?.target_geography||"China"],["Current China status","china_status",initial?.china_status||""]].map(([label,name,value])=><label key={name}><span className="eyebrow text-stone">{label}</span><input name={name} defaultValue={value} className="mt-3 w-full"/></label>)}{[["English terms","keywords_en",join(initial?.keywords_en)],["Chinese terminology","keywords_zh",join(initial?.keywords_zh)],["Formal terminology","formal_terms_zh",join(initial?.formal_terms_zh)],["Procurement terminology","procurement_terms_zh",join(initial?.procurement_terms_zh)],["Regulatory terminology","regulatory_terms_zh",join(initial?.regulatory_terms_zh)],["Distributor terminology","distributor_terms_zh",join(initial?.distributor_terms_zh)]].map(([label,name,value])=><label key={name}><span className="eyebrow text-stone">{label}</span><textarea name={name} defaultValue={value} rows={3} className="mt-3 w-full"/></label>)}</div></details>
  </form>}
