import { AdminClientFilter } from "@/components/china-desk-app/admin-client-filter";
import { Field, OrganizationField, SelectField, Submit, Textarea } from "@/components/china-desk-app/admin-fields";
import { PageHeader, Status } from "@/components/china-desk-app/ui";
import { priorities } from "@/lib/china-desk/constants";
import { type Competitor, getAdminRecords, getOrganizations } from "@/lib/china-desk/data";
import { deleteCompetitor, saveCompetitor } from "../actions";

type AdminCompetitor=Competitor&{organization_id:string;organizations:{name:string}|{name:string}[];competitor_internal_notes?:Array<{content:string}>};
function CompetitorForm({organizations,item}:{organizations:Array<{id:string;name:string}>;item?:AdminCompetitor}){return <form action={saveCompetitor} className="grid gap-6 border-t border-line py-8 md:grid-cols-2"><input type="hidden" name="id" value={item?.id||""}/><OrganizationField organizations={organizations} value={item?.organization_id}/><Field label="Company name" name="company_name" defaultValue={item?.company_name} required/><Field label="Chinese name" name="chinese_name" defaultValue={item?.chinese_name||""}/><Field label="Website" name="website" type="url" defaultValue={item?.website||""}/><Field label="Location" name="location" defaultValue={item?.location||""}/><Field label="Segment" name="segment" defaultValue={item?.segment||""}/><SelectField label="Priority" name="priority" value={item?.priority} options={priorities}/><div className="md:col-span-2"><Textarea label="Description" name="description" defaultValue={item?.description||""} rows={3}/></div><Textarea label="Products, one per line" name="products" defaultValue={item?.products?.join("\n")} rows={4}/><Textarea label="Sources, one per line" name="sources" defaultValue={item?.sources?.join("\n")} rows={4}/><Textarea label="Positioning" name="positioning" defaultValue={item?.positioning||""} rows={3}/><Textarea label="Pricing notes" name="pricing_notes" defaultValue={item?.pricing_notes||""} rows={3}/><Textarea label="Recent activity" name="recent_activity" defaultValue={item?.recent_activity||""} rows={3}/><Textarea label="Client-visible notes" name="external_client_notes" defaultValue={item?.external_client_notes||""} rows={3}/><div className="md:col-span-2"><Textarea label="Internal notes — admin only" name="internal_notes" defaultValue={item?.competitor_internal_notes?.[0]?.content||""} rows={3}/></div><Submit/></form>}
export default async function AdminCompetitorsPage({searchParams}:{searchParams:Promise<{organization?:string}>}){const{organization}=await searchParams;const organizations=await getOrganizations();const items=await getAdminRecords<AdminCompetitor>("competitors",organization,"*,organizations(name),competitor_internal_notes(content)");return <><PageHeader eyebrow="COMPETITORS" title="Maintain the watchlist." description="Keep client-facing intelligence separate from internal working notes."/><AdminClientFilter organizations={organizations} active={organization} basePath="/admin/competitors"/><details className="mb-14"><summary className="cursor-pointer border-b border-ink/25 pb-1 text-sm">Add competitor →</summary><CompetitorForm organizations={organizations}/></details>{items.map(item=>{const org=Array.isArray(item.organizations)?item.organizations[0]:item.organizations;return <details key={item.id} className="border-t border-line py-7"><summary className="cursor-pointer list-none"><div className="grid gap-3 md:grid-cols-12"><div className="md:col-span-6"><h2 className="text-xl font-medium">{item.company_name}</h2><p className="mt-2 text-xs text-stone">{org?.name} · {item.segment}</p></div><p className="text-sm text-stone md:col-span-4">{item.recent_activity}</p><div className="md:col-span-2"><Status>{item.priority}</Status></div></div></summary><CompetitorForm organizations={organizations} item={item}/><form action={deleteCompetitor}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="organization_id" value={item.organization_id}/><button className="text-xs text-accent">Delete competitor</button></form></details>})}</>}
