import type {Metadata} from "next";
import Link from "next/link";
import {redirect} from "next/navigation";
import {MeridianBrand} from "@/components/meridian-brand";
import {SignupForm} from "@/components/signup-form";
import {getWorkspaceContext} from "@/lib/china-desk/auth";
import {productConfig} from "@/config/productConfig";

export const metadata:Metadata={title:`Create account — ${productConfig.name}`,robots:{index:false,follow:false}};export const dynamic="force-dynamic";
export default async function SignupPage({searchParams}:{searchParams:Promise<{website?:string|string[];error?:string|string[]}>}){const context=await getWorkspaceContext();if(context)redirect(context.profile.role==="ADMIN"?"/admin":"/meridian/app");const params=await searchParams;const raw=params.website;const website=(Array.isArray(raw)?raw[0]:raw||"").slice(0,500);const error=Array.isArray(params.error)?params.error[0]:params.error;const errorMessage=error==="verification"?"That verification link is invalid or has expired. Request a fresh link below.":error==="workspace"?"Your email is verified, but Meridian could not prepare your workspace. Please sign in to retry safely.":null;return <main className="min-h-screen bg-paper text-ink"><div className="page-shell flex min-h-screen flex-col py-8 sm:py-12"><header><Link href="/" className="text-[0.62rem] text-stone"><MeridianBrand compact/></Link></header><section className="my-auto w-full max-w-md py-20"><p className="eyebrow text-accent">CLIENT ACCOUNT</p><h1 className="mt-8 text-[clamp(3.6rem,8vw,6.3rem)] font-medium leading-[0.88] tracking-[-0.07em]">Start with China.</h1><p className="mt-6 text-base leading-7 text-charcoal">Tell Meridian what you sell. We’ll prepare your private China opportunity workspace.</p>{errorMessage?<p role="alert" className="mt-8 rounded-xl border border-signal-red/30 bg-signal-red/[0.07] p-4 text-sm leading-6">{errorMessage}</p>:null}<SignupForm website={website}/><p className="mt-8 text-sm text-charcoal">Already have an account? <Link href="/meridian/login" className="text-ink hover:text-accent">Sign in →</Link></p></section><footer className="border-t border-line pt-5 text-xs text-stone">CLIENT accounts only · Private organization-isolated workspace</footer></div></main>}
