import { PageHeader, Status, formatDate } from "@/components/china-desk-app/ui";
import { requireAdmin } from "@/lib/china-desk/auth";
import { createClient } from "@/lib/supabase/server";
import { adjustTokens, grantBetaTokens } from "./actions";
import { currentTimestamp } from "@/lib/server-time";

const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:4}).format(value);
export default async function EconomicsPage({searchParams}:{searchParams:Promise<{notice?:string}>}){
  await requireAdmin();const supabase=await createClient();const params=await searchParams;
  const [orgsResult,lotsResult,jobsResult,reservationsResult,costsResult]=await Promise.all([
    supabase.from("organizations").select("id,name").order("name"),
    supabase.from("token_lots").select("organization_id,kind,initial_tokens,available_tokens,reserved_tokens,expires_at"),
    supabase.from("research_jobs").select("id,organization_id,product_id,research_tier,token_cost,retail_equivalent_usd,accumulated_cogs_usd,cost_status,status,qualified_finding_count,created_at,started_at,completed_at").order("created_at",{ascending:false}).limit(150),
    supabase.from("token_reservations").select("research_job_id,promotional_tokens,purchased_tokens,adjustment_tokens,status,reserved_at"),
    supabase.from("research_cost_events").select("research_job_id,provider,cost_category,cost_type,cost_usd"),
  ]);
  const orgs=orgsResult.data||[],lots=lotsResult.data||[],jobs=jobsResult.data||[],reservations=reservationsResult.data||[],costs=costsResult.data||[];const orgNames=new Map(orgs.map((item)=>[item.id,item.name]));const reservationByJob=new Map(reservations.map((item)=>[item.research_job_id,item]));
  const completed=jobs.filter((item)=>item.status==="COMPLETE"),totalCogs=jobs.reduce((sum,item)=>sum+Number(item.accumulated_cogs_usd||0),0),retail=completed.reduce((sum,item)=>sum+Number(item.retail_equivalent_usd||0),0),qualified=completed.reduce((sum,item)=>sum+Number(item.qualified_finding_count||0),0),promoConsumed=completed.reduce((sum,item)=>sum+Number(reservationByJob.get(item.id)?.promotional_tokens||0),0),paidConsumed=completed.reduce((sum,item)=>sum+Number(reservationByJob.get(item.id)?.purchased_tokens||0),0);const now=currentTimestamp();
  const metrics=[["TOKENS OUTSTANDING",lots.reduce((s,l)=>s+l.available_tokens,0).toString()],["RESEARCH JOBS",jobs.length.toString()],["RESEARCH COGS",money(totalCogs)],["RETAIL EQUIVALENT",money(retail)],["PAID VALUE USED",money(paidConsumed)],["COST / QUALIFIED",qualified?money(totalCogs/qualified):"—"]];
  return <><PageHeader eyebrow="ADMIN · ECONOMICS" title="Research economics." description="Token liability, research cost, margin signal and operational exceptions. Provider cost data never appears in the client workspace."/>
    {params.notice?<p role="status" className="mb-8 border-y border-jade/30 py-4 text-sm text-jade">{params.notice}</p>:null}
    <section className="grid border-y border-line sm:grid-cols-2 xl:grid-cols-6">{metrics.map(([label,value])=><div key={label} className="border-b border-line py-6 sm:px-5 xl:border-b-0 xl:border-r xl:first:pl-0 xl:last:border-r-0"><p className="eyebrow text-stone">{label}</p><p className="mt-4 text-3xl font-medium tracking-[-0.06em]">{value}</p></div>)}</section>
    <div className="mt-16 grid gap-12 xl:grid-cols-2"><form action={grantBetaTokens} className="border-t border-line pt-6"><p className="eyebrow text-accent">BETA ACTIVATION</p><h2 className="mt-4 text-2xl font-medium">Grant 20 promotional Tokens.</h2><p className="mt-3 text-sm leading-6 text-charcoal">Admin-only, one grant per organization. Expires 14 days after activation.</p><select name="organization_id" required className="mt-6 w-full"><option value="">Choose organization</option>{orgs.map((org)=><option key={org.id} value={org.id}>{org.name}</option>)}</select><button className="mt-5 min-h-11 text-sm text-accent">Activate beta allocation →</button></form>
    <form action={adjustTokens} className="border-t border-line pt-6"><p className="eyebrow text-stone">MANUAL ADJUSTMENT</p><h2 className="mt-4 text-2xl font-medium">Correct a balance.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><select name="organization_id" required><option value="">Choose organization</option>{orgs.map((org)=><option key={org.id} value={org.id}>{org.name}</option>)}</select><input name="token_change" type="number" step="1" required placeholder="+10 or -10"/></div><input name="reason" required minLength={3} maxLength={500} className="mt-4 w-full" placeholder="Reason for adjustment"/><button className="mt-5 min-h-11 text-sm text-ink">Record adjustment →</button></form></div>
    <section className="mt-20"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-line pb-5"><div><p className="eyebrow text-stone">JOB ECONOMICS</p><h2 className="mt-3 text-3xl font-medium tracking-[-0.05em]">Research ledger.</h2></div><p className="text-xs text-stone">Promo consumed {promoConsumed} · Paid consumed {paidConsumed}</p></div>{jobs.length?jobs.map((job)=>{const reservation=reservationByJob.get(job.id);const jobCosts=costs.filter((item)=>item.research_job_id===job.id);const unknown=jobCosts.some((item)=>item.cost_type==="UNKNOWN");const stale=["RESERVED","RUNNING"].includes(job.status)&&now-new Date(job.started_at||job.created_at).getTime()>2*60*60*1000;return <article key={job.id} className="grid gap-4 border-b border-line py-6 xl:grid-cols-12 xl:items-center"><div className="xl:col-span-3"><p className="font-medium">{orgNames.get(job.organization_id)||"Organization"}</p><p className="mt-1 font-mono text-[0.58rem] uppercase tracking-[0.1em] text-stone">{job.research_tier} · {job.token_cost} Tokens</p></div><div className="xl:col-span-2"><Status>{stale?"STALE RESERVATION":job.status}</Status></div><div className="text-sm xl:col-span-2"><p>{unknown?"Cost unknown":money(Number(job.accumulated_cogs_usd||0))}</p><p className="mt-1 text-xs text-stone">{job.cost_status}</p></div><div className="text-xs text-stone xl:col-span-2"><p>{reservation?.promotional_tokens||0} promo · {reservation?.purchased_tokens||0} paid</p><p className="mt-1">{job.qualified_finding_count} qualified findings</p></div><div className="text-xs text-stone xl:col-span-3 xl:text-right"><p>{formatDate(job.created_at)}</p><p className="mt-1">{jobCosts.map((item)=>`${item.provider} ${item.cost_type.toLowerCase()}`).join(" · ")||"No provider cost yet"}</p></div></article>}):<p className="py-12 text-sm text-stone">Research jobs will appear after clients begin tokenized research.</p>}</section>
  </>;
}
