import { PageHeader, Status, formatDate } from "@/components/china-desk-app/ui";
import { requireAdmin } from "@/lib/china-desk/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { createOpportunityCandidate, createRegulatoryMatch, ingestEvidence } from "./actions";
import { SearchWorkflow } from "./search-workflow";
import { runMedtechBenchmarks, runUniversalBenchmarks } from "@/lib/meridian-intelligence/benchmarks";

const Field=({label,name,rows=1,required=false,placeholder=""}:{label:string;name:string;rows?:number;required?:boolean;placeholder?:string})=><label className="block"><span className="eyebrow text-stone">{label}</span>{rows>1?<textarea name={name} rows={rows} required={required} placeholder={placeholder} className="mt-3 w-full"/>:<input name={name} required={required} placeholder={placeholder} className="mt-3 w-full"/>}</label>;
type Product={id:string;organization_id:string;product_name:string;organizations:{name:string}|{name:string}[]};
function IdentityFields(){return <div className="grid gap-5 sm:grid-cols-2"><Field label="Organization ID" name="organization_id" required/><Field label="Product ID" name="product_id" required/></div>}

export default async function MedtechIntelligencePage({searchParams}:{searchParams:Promise<{plan?:string}>}){await requireAdmin();const params=await searchParams;const admin=createAdminClient();const [productsResult,evidenceResult,logsResult]=await Promise.all([admin.from("product_profiles").select("id,organization_id,product_name,organizations(name)").order("updated_at",{ascending:false}),admin.from("evidence").select("id,product_id,source_title,source_url,source_type,extracted_fact,verification_status,retrieved_at").order("retrieved_at",{ascending:false}).limit(30),admin.from("retrieval_logs").select("id,event_type,status,message,source_url,created_at").order("created_at",{ascending:false}).limit(30)]);const products=(productsResult.data||[]) as Product[];
  const benchmarkResults=[...runUniversalBenchmarks(),...runMedtechBenchmarks().map((item)=>({...item,overlay:"MEDTECH",overlayMatches:true,expectedIntentPresent:item.prioritizesDistributors,avoidsMedtechOnlyQueries:false}))];
  return <><PageHeader eyebrow="INTELLIGENCE SEARCH" title="From source to commercial action." description="Cross-industry operator controls for product profiles, real search, evidence, scoring and opportunity creation. Medtech regulatory tools appear only when relevant. Nothing is published without provenance."/>
    <SearchWorkflow selectedPlanId={params.plan}/>
    <section className="mt-20 border-t border-line pt-8"><p className="eyebrow text-stone">DETERMINISTIC CALIBRATION FIXTURES</p><div className="mt-5 border-t border-line">{benchmarkResults.map((item)=><article key={item.name} className="grid gap-3 border-b border-line py-5 sm:grid-cols-12"><p className="font-medium sm:col-span-5">{item.name}</p><p className="text-xs text-stone sm:col-span-3">{item.overlay} overlay</p><div className="sm:col-span-4"><Status>{item.overlayMatches&&item.expectedIntentPresent?"PASS":"REVIEW"}</Status></div></article>)}</div></section>
    <section><p className="eyebrow text-stone">PRODUCT REFERENCE</p><div className="mt-5 border-t border-line">{products.map((product)=>{const org=Array.isArray(product.organizations)?product.organizations[0]:product.organizations;return <div key={product.id} className="grid gap-2 border-b border-line py-4 text-xs sm:grid-cols-3"><span>{org?.name} · {product.product_name}</span><code className="text-stone">Org: {product.organization_id}</code><code className="text-stone">Product: {product.id}</code></div>})}</div></section>
    <section className="mt-20 grid gap-12 xl:grid-cols-3"><details open className="border-t border-line pt-6"><summary className="cursor-pointer text-xl font-medium">1. Retrieve evidence</summary><form action={ingestEvidence} className="mt-7 space-y-5"><IdentityFields/><Field label="Source URL" name="source_url" required/><Field label="Extracted fact" name="extracted_fact" rows={4} required placeholder="A bounded fact supported by this page."/><Field label="Fact type" name="fact_type" placeholder="PRODUCT_PORTFOLIO"/><label><span className="eyebrow text-stone">Confidence</span><select name="confidence" className="mt-3 w-full"><option>MEDIUM</option><option>HIGH</option><option>LOW</option></select></label><Field label="Regulatory relevance" name="regulatory_relevance" rows={2}/><Field label="Commercial relevance" name="commercial_relevance" rows={2}/><button className="text-sm font-medium text-accent">Retrieve and store evidence →</button></form></details>
      <details className="border-t border-line pt-6"><summary className="cursor-pointer text-xl font-medium">2. Create regulatory match</summary><form action={createRegulatoryMatch} className="mt-7 space-y-5"><IdentityFields/><Field label="Authority" name="authority" required/><Field label="Document name" name="document_name" required/><Field label="Document number" name="document_number"/><Field label="Document type" name="document_type"/><Field label="Source URL" name="source_url"/><label><span className="eyebrow text-stone">Status</span><select name="status" className="mt-3 w-full"><option>UNCERTAIN</option><option>POSSIBLE</option><option>LIKELY</option><option>NEEDS_EXPERT_REVIEW</option></select></label><label><span className="eyebrow text-stone">Confidence</span><select name="confidence" className="mt-3 w-full"><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><Field label="Applicability" name="applicability" required/><Field label="Why this may apply" name="applicability_reason" rows={4} required/><Field label="Requirements summary" name="requirements_summary" rows={4}/><Field label="Questions to validate · one per line" name="questions_to_validate" rows={4}/><Field label="Evidence IDs · one per line" name="evidence_ids" rows={3}/><button className="text-sm font-medium text-accent">Store regulatory match →</button></form></details>
      <details className="border-t border-line pt-6"><summary className="cursor-pointer text-xl font-medium">3. Create opportunity</summary><form action={createOpportunityCandidate} className="mt-7 space-y-5"><IdentityFields/><Field label="Company name" name="company_name" required/><Field label="Chinese name" name="chinese_name"/><Field label="Location" name="location"/><Field label="Website" name="website"/><Field label="Company overview" name="description" rows={4}/><label><span className="eyebrow text-stone">Fit assessment</span><select name="overall_assessment" className="mt-3 w-full"><option>INSUFFICIENT_EVIDENCE</option><option>POSSIBLE_FIT</option><option>STRONG_FIT</option><option>VERY_STRONG_FIT</option><option>WEAK_FIT</option></select></label><label><span className="eyebrow text-stone">Confidence</span><select name="confidence" className="mt-3 w-full"><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><Field label="Why it matters · one per line" name="why_it_matters" rows={4}/><Field label="Concerns · one per line" name="concerns" rows={3}/><Field label="Unknowns · one per line" name="unknowns" rows={4}/><Field label="Recommended next action" name="next_action" rows={3}/><Field label="Evidence IDs · one per line" name="evidence_ids" rows={3}/><button className="text-sm font-medium text-accent">Create opportunity candidate →</button></form></details>
    </section>
    <section className="mt-24 grid gap-16 xl:grid-cols-2"><div><p className="eyebrow text-stone">RECENT EVIDENCE</p><div className="mt-5 border-t border-line">{(evidenceResult.data||[]).map((item)=><article key={item.id} className="border-b border-line py-5"><div className="flex justify-between gap-4"><Status>{item.verification_status}</Status><code className="text-[0.62rem] text-stone">{item.id}</code></div><p className="mt-4 text-sm leading-6">{item.extracted_fact}</p><a href={item.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs text-stone">{item.source_title} ↗</a></article>)}</div></div><div><p className="eyebrow text-stone">RETRIEVAL DIAGNOSTICS</p><div className="mt-5 border-t border-line">{(logsResult.data||[]).map((item)=><article key={item.id} className="border-b border-line py-5"><div className="flex justify-between gap-4"><Status>{item.event_type}</Status><span className="text-xs text-stone">{formatDate(item.created_at)}</span></div><p className="mt-3 text-sm">{item.message||item.status}</p></article>)}</div></div></section>
  </>;
}
