"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/china-desk/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { retrieveIntelligencePage } from "@/lib/meridian-intelligence/retrieval";
import { DeterministicEvidenceExtractor } from "@/lib/search/evidence-extraction";
import { getSearchProvider, searchProviderConfiguration } from "@/lib/search/provider";
import { MeridianSearchRunner } from "@/lib/search/runner";

const value=(form:FormData,key:string,max=5000)=>String(form.get(key)||"").trim().slice(0,max);
async function resultFor(id:string){const admin=createAdminClient();const {data,error}=await admin.from("search_results").select("*,query_plans(query,product_terms,rationale,intent)").eq("id",id).single();if(error||!data)throw new Error("Search result not found.");return{admin,result:data};}

export async function runSearch(form:FormData){await requireAdmin();const organizationId=value(form,"organization_id",100),productId=value(form,"product_id",100),queryPlanId=value(form,"query_plan_id",100);await new MeridianSearchRunner().run({organizationId,productId,queryPlanId});revalidatePath("/admin/medtech");redirect(`/admin/medtech?plan=${queryPlanId}`);}

export async function runBenchmarkSearches(form:FormData){await requireAdmin();const organizationId=value(form,"organization_id",100),productId=value(form,"product_id",100);const admin=createAdminClient();const {data,error}=await admin.from("query_plans").select("id,intent").eq("organization_id",organizationId).eq("product_id",productId).in("intent",["FIND_REGULATION","DISCOVER_DISTRIBUTORS","FIND_TENDERS"]).order("created_at",{ascending:false});if(error)throw new Error(error.message);const unique=new Map<string,string>();for(const plan of data||[])if(!unique.has(plan.intent))unique.set(plan.intent,plan.id);if(unique.size!==3)throw new Error("This product needs regulation, distributor and tender QueryPlans before running the benchmark.");for(const queryPlanId of unique.values())await new MeridianSearchRunner().run({organizationId,productId,queryPlanId});const first=[...unique.values()][0];revalidatePath("/admin/medtech");redirect(`/admin/medtech?plan=${first}`);}

export async function fetchSearchResult(form:FormData){await requireAdmin();const id=value(form,"search_result_id",100);const {admin,result}=await resultFor(id);const planValue=result.query_plans;const plan=Array.isArray(planValue)?planValue[0]:planValue;
  try{const page=await retrieveIntelligencePage(result.url);const suggestions=await new DeterministicEvidenceExtractor().suggest({content:page.text,query:plan?.query||"",productTerms:plan?.product_terms||[]});const {error}=await admin.from("search_results").update({status:"FETCHED",fetched_at:page.retrievedAt,extracted_title:page.title,extracted_text:page.text,suggested_fact:suggestions[0]?.text||null,fetch_error:null,metadata:{...(result.metadata||{}),suggestion_reason:suggestions[0]?.reason||null}}).eq("id",id).eq("organization_id",result.organization_id);if(error)throw new Error(error.message);await admin.from("source_registry").update({last_successful_retrieval_at:page.retrievedAt,last_error:null}).eq("id",result.source_id).eq("organization_id",result.organization_id);const {data:run}=await admin.from("search_runs").select("fetch_count").eq("id",result.search_run_id).single();await admin.from("search_runs").update({fetch_count:Number(run?.fetch_count||0)+1}).eq("id",result.search_run_id);await admin.from("retrieval_logs").insert({organization_id:result.organization_id,product_id:result.product_id,query_plan_id:result.query_plan_id,event_type:"URL_RETRIEVED",source_url:page.url,message:`Fetched ${page.title||result.title}`,metadata:{search_result_id:id,search_run_id:result.search_run_id}});
  }catch(error){const message=error instanceof Error?error.message:"Retrieval failed.";await admin.from("search_results").update({fetch_error:message}).eq("id",id).eq("organization_id",result.organization_id);const {data:source}=await admin.from("source_registry").select("failure_count").eq("id",result.source_id).single();await admin.from("source_registry").update({last_failure_at:new Date().toISOString(),failure_count:Number(source?.failure_count||0)+1,last_error:message}).eq("id",result.source_id);await admin.from("retrieval_logs").insert({organization_id:result.organization_id,product_id:result.product_id,query_plan_id:result.query_plan_id,event_type:"RETRIEVAL_FAILED",source_url:result.url,status:"FAILED",message,metadata:{search_result_id:id,search_run_id:result.search_run_id}});throw error;}
  revalidatePath("/admin/medtech");
}

export async function rejectSearchResult(form:FormData){await requireAdmin();const id=value(form,"search_result_id",100);const {admin,result}=await resultFor(id);await admin.from("search_results").update({status:"REJECTED"}).eq("id",id).eq("organization_id",result.organization_id);await admin.from("retrieval_logs").insert({organization_id:result.organization_id,product_id:result.product_id,query_plan_id:result.query_plan_id,event_type:"RESULT_REJECTED",source_url:result.url,message:"Rejected by operator",metadata:{search_result_id:id}});revalidatePath("/admin/medtech");}

export async function saveSearchEvidence(form:FormData){await requireAdmin();const id=value(form,"search_result_id",100),fact=value(form,"extracted_fact");if(!fact)throw new Error("A reviewed fact is required.");const {admin,result}=await resultFor(id);if(result.status!=="FETCHED"||!result.extracted_text)throw new Error("Fetch and review the page before creating evidence.");const {error}=await admin.from("evidence").insert({organization_id:result.organization_id,product_id:result.product_id,query_plan_id:result.query_plan_id,search_result_id:result.id,source_id:result.source_id,source_url:result.url,source_title:result.extracted_title||result.title,source_type:result.source_type,retrieved_at:result.fetched_at||new Date().toISOString(),published_at:result.published_at,language:/[\u3400-\u9fff]/.test(result.extracted_text)?"zh-CN":"unknown",extracted_fact:fact,fact_type:value(form,"fact_type",160)||"SOURCE_STATEMENT",confidence:value(form,"confidence",20)||"MEDIUM",verification_status:"SOURCE_CONFIRMED",commercial_relevance:value(form,"commercial_relevance",20)||"MEDIUM",regulatory_relevance:value(form,"regulatory_relevance",20)||"LOW",authority_score:result.source_authority==="PRIMARY"?100:result.source_authority==="HIGH"?80:result.source_authority==="MEDIUM"?60:35,relevance_score:result.meridian_score,metadata:{search_run_id:result.search_run_id,provider:result.provider,provider_rank:result.provider_rank,meridian_rank:result.meridian_rank,operator_reviewed:true}});if(error)throw new Error(error.message);await admin.from("search_results").update({status:"EVIDENCE_CREATED"}).eq("id",id);const {data:run}=await admin.from("search_runs").select("evidence_count").eq("id",result.search_run_id).single();await admin.from("search_runs").update({evidence_count:Number(run?.evidence_count||0)+1}).eq("id",result.search_run_id);await admin.from("retrieval_logs").insert({organization_id:result.organization_id,product_id:result.product_id,query_plan_id:result.query_plan_id,event_type:"EVIDENCE_EXTRACTED",source_url:result.url,message:fact,metadata:{search_result_id:id,search_run_id:result.search_run_id}});revalidatePath("/admin/medtech");revalidatePath("/meridian/app/regulatory");revalidatePath("/meridian/app/partners");}

export async function testSearchProvider(){const context=await requireAdmin();const config=searchProviderConfiguration();const checkedAt=new Date().toISOString();let health={provider:config.provider,configured:config.configured,healthy:false,latencyMs:null as number|null,resultCount:null as number|null,error:config.configured?null:"SEARCH PROVIDER NOT CONFIGURED"};if(config.configured)health=await getSearchProvider().healthCheck();const admin=createAdminClient();await admin.from("search_provider_checks").insert({provider:health.provider,configured:health.configured,healthy:health.healthy,query:"site:nmpa.gov.cn 医疗器械",latency_ms:health.latencyMs,result_count:health.resultCount,error_message:health.error,checked_by:context.user.id,checked_at:checkedAt});revalidatePath("/admin/medtech");}
