import Link from "next/link";
import { EmptyState, PageHeader, Status, formatDate } from "@/components/china-desk-app/ui";
import { requireWorkspace } from "@/lib/china-desk/auth";
import { getProductIntelligence, getProductProfiles } from "@/lib/meridian-intelligence/data";

function freshness(item:{verification_status:string;stale_after:string|null}){
  if(item.verification_status==="HUMAN_VERIFIED") return "HUMAN VERIFIED";
  if(item.verification_status==="STALE"||(item.stale_after&&new Date(item.stale_after)<new Date())) return "STALE";
  return "CURRENT";
}

export default async function RegulatoryMapPage({searchParams}:{searchParams:Promise<{product?:string}>}){
  const context=await requireWorkspace(); const profiles=await getProductProfiles(context.organization!.id); const params=await searchParams;
  const product=profiles.find((item)=>item.id===params.product)||profiles[0];
  if(!product) return <><PageHeader eyebrow="REGULATORY MAP" title="Understand the path before you enter."/><EmptyState title="Create a Product Profile first." description="Meridian needs the product, intended use and China terminology before it can map regulatory evidence."/></>;
  const {matches,evidence}=await getProductIntelligence(context.organization!.id,product.id);
  const regulatoryEvidence=evidence.filter((item)=>item.regulatory_relevance||item.source_type==="AUTHORITATIVE");
  return <><PageHeader eyebrow="REGULATORY MAP" title={product.product_name} description="A working evidence map—not a legal conclusion. Unverified requirements remain visibly uncertain." action={<Link href={`/meridian/app/product?id=${product.id}`} className="text-xs text-stone hover:text-accent">Edit product profile →</Link>}/>
    <div className="grid gap-px overflow-hidden rounded-2xl border border-line bg-line md:grid-cols-3">{[["LIKELY CLASSIFICATION",matches[0]?.applicability||"Needs validation"],["AUTHORITY",matches[0]?.authority||"NMPA / competent authority to confirm"],["OPEN QUESTIONS",matches.reduce((sum,item)=>sum+item.questions_to_validate.length,0)||3]].map(([label,value])=><section key={label} className="bg-elevated p-7"><p className="eyebrow text-stone">{label}</p><p className="mt-7 text-2xl font-medium tracking-[-0.045em]">{value}</p>{label==="LIKELY CLASSIFICATION"?<p className="mt-4 text-xs text-stone">{matches[0]?.confidence||"LOW"} CONFIDENCE · NEEDS PROFESSIONAL CONFIRMATION</p>:null}</section>)}</div>
    <section className="mt-20"><div className="flex items-end justify-between border-b border-line pb-5"><div><p className="eyebrow text-stone">RELEVANT REQUIREMENTS</p><h2 className="mt-4 text-3xl font-medium tracking-[-0.05em]">Why this may apply.</h2></div></div>{matches.length?<div>{matches.map((match)=><article key={match.id} className="border-b border-line py-8"><div className="grid gap-6 md:grid-cols-12"><div className="md:col-span-3"><Status>{match.status}</Status><p className="mt-4 text-xs text-stone">{match.confidence} confidence</p></div><div className="md:col-span-5"><h3 className="text-xl font-medium">{match.document_name}</h3><p className="mt-2 text-xs text-stone">{match.authority}{match.document_number?` · ${match.document_number}`:""}</p><p className="mt-5 text-sm leading-6 text-charcoal">{match.requirements_summary||"Needs validation"}</p></div><div className="md:col-span-4"><p className="eyebrow text-stone">WHY THIS APPLIES</p><p className="mt-3 text-sm leading-6">{match.applicability_reason}</p><p className="mt-5 text-xs text-stone">Last checked {formatDate(match.last_checked_at)}</p>{match.source_url?<a href={match.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs text-accent">Source ↗</a>:null}</div></div>{match.questions_to_validate.length?<div className="mt-7 border-t border-line pt-5"><p className="eyebrow text-stone">QUESTIONS THAT MAY CHANGE THIS</p><ul className="mt-4 space-y-2 text-sm text-charcoal">{match.questions_to_validate.map((question)=><li key={question}>— {question}</li>)}</ul></div>:null}</article>)}</div>:<EmptyState title="No regulatory matches yet." description="This is a successful unknown: official evidence has not yet been matched to this product. Use the structured query plan for primary-source research."/>}</section>
    <section className="mt-24"><p className="eyebrow text-stone">SOURCE EVIDENCE</p><h2 className="mt-4 text-3xl font-medium tracking-[-0.05em]">Facts before assessment.</h2>{regulatoryEvidence.length?<div className="mt-8 border-t border-line">{regulatoryEvidence.map((item)=><article key={item.id} className="grid gap-5 border-b border-line py-7 md:grid-cols-12"><div className="md:col-span-2"><Status>{freshness(item)}</Status></div><div className="md:col-span-6"><p className="eyebrow text-accent">FACT</p><p className="mt-3 leading-7">{item.extracted_fact}</p><p className="mt-3 text-xs text-stone">{item.fact_type} · {item.confidence} confidence</p></div><div className="md:col-span-4"><a href={item.source_url} target="_blank" rel="noreferrer" className="text-sm hover:text-accent">{item.source_title} ↗</a><p className="mt-3 text-xs text-stone">Retrieved {formatDate(item.retrieved_at)}</p></div></article>)}</div>:<p className="mt-7 text-sm text-stone">No primary-source evidence has been stored for this product yet.</p>}</section>
  </>;
}

