import Link from "next/link";
import { AnalyticsLink } from "@/components/analytics-link";
import { TrackedSubmit } from "@/components/tracked-submit";
import { EmptyState, PageHeader, Status } from "@/components/china-desk-app/ui";
import { requireWorkspace } from "@/lib/china-desk/auth";
import { humanize, partnerStatuses } from "@/lib/china-desk/constants";
import { getPartners } from "@/lib/china-desk/data";
import { logOpportunityInteraction, requestLocalVerification, updateOpportunity } from "./actions";

type Opportunity = Awaited<ReturnType<typeof getPartners>>[number];

function fit(item: Opportunity) {
  const raw = item.ai_assessment?.score ?? item.ai_assessment?.fitScore ?? item.ai_assessment?.fit;
  const number = Number(raw);
  return Number.isFinite(number) ? Math.max(0, Math.min(100, Math.round(number))) : null;
}

export default async function OpportunitiesPage({ searchParams }: { searchParams: Promise<{ view?: string; opportunity?: string }> }) {
  const context = await requireWorkspace();
  const items = await getPartners(context.organization!.id);
  const params = await searchParams;
  const pipeline = params.view === "pipeline";
  const selected = items.find((item) => item.id === params.opportunity);

  return <>
    <PageHeader eyebrow="OPPORTUNITIES" title="Find the right companies." description="Customers, distributors, suppliers and partners—kept with the evidence, fit assessment and next action attached." action={<Link href={pipeline ? "/meridian/app/partners" : "/meridian/app/partners?view=pipeline"} className="text-xs text-stone transition-colors hover:text-accent">{pipeline ? "Opportunity map" : "Pipeline"} →</Link>} />
    {!items.length ? <EmptyState title="No opportunities discovered yet." description="Relevant companies will appear here as the opportunity engine and reviewed research add them." /> : pipeline ? <Pipeline items={items} /> : <OpportunityList items={items} />}
    {selected ? <OpportunityDrawer selected={selected} pipeline={pipeline} /> : null}
  </>;
}

function Pipeline({ items }: { items: Opportunity[] }) {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{partnerStatuses.map((status)=><section key={status} className="min-h-56 rounded-2xl border border-line bg-elevated p-4"><div className="flex justify-between border-b border-line pb-3"><h2 className="text-sm font-medium">{status === "IDENTIFIED" ? "Discovered" : humanize(status)}</h2><span className="font-mono text-[0.65rem] text-stone">{items.filter((item)=>item.status===status).length}</span></div>{items.filter((item)=>item.status===status).map((item)=><AnalyticsLink eventName="opportunity_viewed" eventLocation="client-pipeline" key={item.id} href={`/meridian/app/partners?view=pipeline&opportunity=${item.id}`} className="block border-b border-line py-5 last:border-b-0"><div className="flex justify-between gap-3"><h3 className="font-medium">{item.company_name}</h3>{fit(item) !== null ? <span className="text-lg font-medium text-accent">{fit(item)}</span> : null}</div><p className="mt-2 text-xs text-stone">{item.partner_type} · {item.location}</p><p className="mt-4 text-xs leading-5 text-charcoal">{item.notes}</p></AnalyticsLink>)}</section>)}</div>;
}

function OpportunityList({ items }: { items: Opportunity[] }) {
  return <div className="border-t border-line"><div className="hidden grid-cols-12 gap-5 border-b border-line py-4 font-mono text-[0.58rem] uppercase tracking-[0.1em] text-stone md:grid"><span className="col-span-3">Company</span><span className="col-span-2">Type</span><span className="col-span-4">Why it matters</span><span className="col-span-2">Stage</span><span>Fit</span></div>{items.map((item)=><AnalyticsLink eventName="opportunity_viewed" eventLocation="client-opportunity-map" key={item.id} href={`/meridian/app/partners?opportunity=${item.id}`} className="grid gap-3 border-b border-line py-7 transition-colors hover:bg-white/[0.025] md:grid-cols-12 md:items-center md:px-4"><div className="md:col-span-3"><h2 className="text-xl font-medium">{item.company_name}</h2><p className="mt-1 text-xs text-stone">{item.chinese_name || item.location || "China"}</p></div><p className="text-sm text-stone md:col-span-2">{item.partner_type}</p><p className="text-sm leading-6 text-charcoal md:col-span-4">{item.ai_assessment ? String(item.ai_assessment.rationale || item.ai_assessment.why || item.notes || "Assessment in preparation") : item.notes || "Assessment in preparation"}</p><div className="md:col-span-2"><Status>{item.status === "IDENTIFIED" ? "DISCOVERED" : item.status}</Status></div><div>{fit(item) !== null ? <><span className="text-2xl font-medium tracking-[-0.05em] text-accent">{fit(item)}</span><span className="ml-1 text-xs text-stone">/100</span></> : <span className="text-xs text-stone">Preparing</span>}</div></AnalyticsLink>)}</div>;
}

function OpportunityDrawer({ selected, pipeline }: { selected: Opportunity; pipeline: boolean }) {
  return <div className="fixed inset-0 z-50 bg-black/65 backdrop-blur-sm"><aside className="ml-auto h-full w-full max-w-2xl overflow-y-auto border-l border-line bg-elevated p-6 shadow-[var(--shadow-elevated)] sm:p-10"><div className="flex items-center justify-between"><Status>{selected.status === "IDENTIFIED" ? "DISCOVERED" : selected.status}</Status><Link href={pipeline ? "/meridian/app/partners?view=pipeline" : "/meridian/app/partners"} className="text-sm text-stone hover:text-ink">Close</Link></div><div className="mt-10 flex items-end justify-between gap-6"><div><p className="eyebrow text-stone">MERIDIAN OPPORTUNITY</p><h2 className="mt-4 text-[clamp(2.7rem,6vw,5rem)] font-medium leading-[0.9] tracking-[-0.065em]">{selected.company_name}</h2><p className="mt-3 text-charcoal">{selected.chinese_name} · {selected.location}</p></div>{fit(selected) !== null ? <div className="text-right"><p className="text-5xl font-medium tracking-[-0.07em] text-accent">{fit(selected)}</p><p className="mt-1 font-mono text-[0.55rem] uppercase tracking-[0.1em] text-stone">Meridian fit / 100</p></div> : null}</div>
    <div className="mt-10 grid gap-7 border-y border-line py-7 sm:grid-cols-2">{[["Company type",selected.partner_type],["Website",selected.website],["Contact",selected.contact_person],["Role",selected.contact_role],["Email",selected.email],["WeChat",selected.wechat]].map(([label,value])=>value?<div key={label}><p className="eyebrow text-stone">{label}</p><p className="mt-2 text-sm">{value}</p></div>:null)}</div>
    {selected.ai_assessment ? <section className="mt-10"><p className="eyebrow text-accent">MERIDIAN ASSESSMENT</p><p className="mt-4 text-sm leading-7 text-charcoal">This is an explainable working assessment, not a scientifically validated score.</p><div className="mt-6 space-y-5">{Object.entries(selected.ai_assessment).filter(([key])=>!["score","fit","fitScore"].includes(key)).map(([key,value])=><div key={key} className="border-t border-line pt-4"><p className="eyebrow text-stone">{key.replaceAll(/([A-Z])/g," $1")}</p><p className="mt-3 text-sm leading-6">{Array.isArray(value)?value.join(" · "):String(value??"")}</p></div>)}</div></section> : <p className="mt-10 text-sm text-stone">A full fit explanation is being prepared.</p>}
    <details className="mt-12 border-t border-line pt-6"><summary className="cursor-pointer text-lg font-medium">Update opportunity →</summary><form action={updateOpportunity} className="mt-7 grid gap-5 sm:grid-cols-2"><input type="hidden" name="id" value={selected.id}/><label><span className="eyebrow text-stone">Pipeline stage</span><select name="status" defaultValue={selected.status} className="mt-3 w-full"><option value="IDENTIFIED">Discovered</option>{partnerStatuses.filter((status)=>status!=="IDENTIFIED").map((status)=><option key={status}>{status}</option>)}</select></label><label><span className="eyebrow text-stone">Contact person</span><input name="contact_person" defaultValue={selected.contact_person||""} className="mt-3 w-full"/></label><label><span className="eyebrow text-stone">Role</span><input name="contact_role" defaultValue={selected.contact_role||""} className="mt-3 w-full"/></label><label><span className="eyebrow text-stone">Email</span><input name="email" type="email" defaultValue={selected.email||""} className="mt-3 w-full"/></label><label><span className="eyebrow text-stone">Phone</span><input name="phone" defaultValue={selected.phone||""} className="mt-3 w-full"/></label><label><span className="eyebrow text-stone">WeChat</span><input name="wechat" defaultValue={selected.wechat||""} className="mt-3 w-full"/></label><label className="sm:col-span-2"><span className="eyebrow text-stone">Internal team notes</span><textarea name="notes" rows={3} defaultValue={selected.notes||""} className="mt-3 w-full"/></label><TrackedSubmit eventName="partner_added_pipeline" className="w-fit rounded-lg bg-accent px-4 py-2.5 text-sm font-medium text-[#071018]">Save opportunity →</TrackedSubmit></form></details>
    <details className="mt-8 border-t border-line pt-6"><summary className="cursor-pointer text-lg font-medium">Log an interaction →</summary><form action={logOpportunityInteraction} className="mt-7 space-y-5"><input type="hidden" name="id" value={selected.id}/><label className="block"><span className="eyebrow text-stone">Type</span><select name="interaction_type" className="mt-3 w-full"><option>EMAIL</option><option>WECHAT</option><option>CALL</option><option>REPLY</option><option>NOTE</option><option>REMINDER</option></select></label><label className="block"><span className="eyebrow text-stone">Record</span><textarea name="content" required rows={3} className="mt-3 w-full" placeholder="What happened, what was learned, and what comes next?"/></label><label className="block"><span className="eyebrow text-stone">Follow-up reminder · optional</span><input name="follow_up_at" type="datetime-local" className="mt-3 w-full"/></label><button className="rounded-lg border border-line-strong px-4 py-2.5 text-sm">Add to history →</button></form></details>
    <form action={requestLocalVerification} className="mt-10 rounded-2xl border border-accent/25 bg-accent/[0.06] p-6"><input type="hidden" name="id" value={selected.id}/><input type="hidden" name="company" value={selected.company_name}/><p className="eyebrow text-accent">OPTIONAL HUMAN LAYER</p><p className="mt-4 text-sm leading-6 text-charcoal">Request China-side checks when company registration, portfolio, contact identity or market reputation needs additional confidence.</p><TrackedSubmit eventName="verification_requested" className="mt-6 text-sm font-medium text-accent">Request local verification →</TrackedSubmit></form>
    </aside></div>;
}
