import Link from "next/link";
import { PageHeader, Status } from "@/components/china-desk-app/ui";
import { requireWorkspace } from "@/lib/china-desk/auth";
import { getProductIntelligence, getProductProfiles } from "@/lib/meridian-intelligence/data";
import { generateQueryPlan, saveProductProfile } from "./actions";

const join=(items:string[])=>items.join("\n");
const Field=({label,name,value="",rows=1,placeholder=""}:{label:string;name:string;value?:string;rows?:number;placeholder?:string})=><label className="block"><span className="eyebrow text-stone">{label}</span>{rows>1?<textarea name={name} defaultValue={value} rows={rows} placeholder={placeholder} className="mt-3 w-full"/>:<input name={name} defaultValue={value} placeholder={placeholder} className="mt-3 w-full"/>}</label>;

export default async function ProductPage({searchParams}:{searchParams:Promise<{id?:string}>}){
  const context=await requireWorkspace(); const profiles=await getProductProfiles(context.organization!.id); const params=await searchParams;
  const selected=profiles.find((item)=>item.id===params.id)||profiles[0]||null;
  const intelligence=selected?await getProductIntelligence(context.organization!.id,selected.id):null;
  return <><PageHeader eyebrow="PRODUCT PROFILE" title="What Meridian thinks you sell." description="A structured, editable product memory for China terminology, regulation and opportunity discovery." action={selected?<Link href="/meridian/app/regulatory" className="text-xs text-stone hover:text-accent">Regulatory Map →</Link>:undefined}/>
    {profiles.length>1?<nav className="mb-10 flex flex-wrap gap-4" aria-label="Products">{profiles.map((profile)=><Link key={profile.id} href={`/meridian/app/product?id=${profile.id}`} className={`text-sm ${profile.id===selected?.id?"text-accent":"text-stone"}`}>{profile.product_name}</Link>)}</nav>:null}
    <form action={saveProductProfile} className="grid gap-10 xl:grid-cols-12"><input type="hidden" name="id" value={selected?.id||""}/>
      <section className="space-y-7 xl:col-span-7"><h2 className="text-3xl font-medium tracking-[-0.05em]">Product identity</h2><div className="grid gap-6 sm:grid-cols-2"><Field label="Product" name="product_name" value={selected?.product_name} placeholder="Portable wireless EEG system"/><Field label="Company" name="company_name" value={selected?.company_name||""}/><Field label="Company URL" name="company_url" value={selected?.company_url||""}/><Field label="China objective" name="business_goal" value={selected?.business_goal||""} placeholder="Find distributors in China"/><div className="sm:col-span-2"><Field label="Product description" name="product_description" value={selected?.product_description||""} rows={4}/></div><Field label="Intended use" name="intended_use" value={selected?.intended_use||""} rows={3}/><Field label="Clinical use" name="clinical_use" value={selected?.clinical_use||""} rows={3}/><Field label="Target customers" name="target_customer" value={selected?.target_customer||""} rows={3}/><Field label="Target departments" name="target_department" value={selected?.target_department||""} rows={3}/><Field label="Market segment" name="target_market_segment" value={selected?.target_market_segment||""}/><Field label="Target geography" name="target_geography" value={selected?.target_geography||"China"}/><div className="sm:col-span-2"><Field label="Current China status" name="china_status" value={selected?.china_status||""} rows={3}/></div></div></section>
      <aside className="xl:col-span-4 xl:col-start-9"><div className="sticky top-10 border-t border-line pt-7"><div className="flex items-center justify-between"><h2 className="text-xl font-medium">China search language</h2>{selected?<Status>{selected.terminology_status}</Status>:null}</div><p className="mt-4 text-sm leading-6 text-stone">One term per line. Generated terms remain provisional until you or Meridian confirms them.</p><div className="mt-7 space-y-6"><Field label="English product terms" name="keywords_en" value={join(selected?.keywords_en||[]) } rows={3}/><Field label="Product terms · 中文" name="keywords_zh" value={join(selected?.keywords_zh||[])} rows={3}/><Field label="Formal terms · 中文" name="formal_terms_zh" value={join(selected?.formal_terms_zh||[])} rows={3}/><Field label="Distributor terms · 中文" name="distributor_terms_zh" value={join(selected?.distributor_terms_zh||[])} rows={3}/><Field label="Procurement terms · 中文" name="procurement_terms_zh" value={join(selected?.procurement_terms_zh||[])} rows={3}/><Field label="Regulatory terms · 中文" name="regulatory_terms_zh" value={join(selected?.regulatory_terms_zh||[])} rows={3}/></div><button className="mt-8 text-sm font-medium text-accent">Save product profile →</button></div></aside>
    </form>
    {selected?<section className="mt-24 border-t border-line pt-10"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-stone">CHINA QUERY PLANNER</p><h2 className="mt-4 text-3xl font-medium tracking-[-0.05em]">What we need to know.</h2></div><form action={generateQueryPlan}><input type="hidden" name="id" value={selected.id}/><button className="text-sm text-accent">Generate structured query plan →</button></form></div>{intelligence?.queries.length?<div className="mt-8 border-t border-line">{intelligence.queries.map((query)=><article key={query.id} className="grid gap-4 border-b border-line py-6 md:grid-cols-12"><div className="md:col-span-3"><Status>{query.intent}</Status><p className="mt-3 text-xs text-stone">Priority {query.priority}</p></div><div className="md:col-span-5"><p className="text-lg">{query.query}</p><p className="mt-2 text-xs text-stone">{query.query_language}</p></div><p className="text-sm leading-6 text-charcoal md:col-span-4">{query.rationale}</p></article>)}</div>:<p className="mt-7 text-sm text-stone">No query plan yet. Meridian will plan source-specific searches after the product language is ready.</p>}</section>:null}
  </>;
}

