import { AdminClientFilter } from "@/components/china-desk-app/admin-client-filter";
import { Field, OrganizationField, SelectField, Submit, Textarea } from "@/components/china-desk-app/admin-fields";
import { PageHeader, Status } from "@/components/china-desk-app/ui";
import { partnerStatuses } from "@/lib/china-desk/constants";
import { type Partner, getAdminRecords, getOrganizations } from "@/lib/china-desk/data";
import { deletePartner, savePartner } from "../actions";

const partnerTypes=["Distributor","Customer","Supplier","Agency","Broker","Strategic Partner","Other"] as const;
type AdminPartner=Partner&{organization_id:string;organizations:{name:string}|{name:string}[];partner_internal_notes?:Array<{content:string}>};
function PartnerForm({organizations,item}:{organizations:Array<{id:string;name:string}>;item?:AdminPartner}){return <form action={savePartner} className="grid gap-6 border-t border-line py-8 md:grid-cols-2"><input type="hidden" name="id" value={item?.id||""}/><OrganizationField organizations={organizations} value={item?.organization_id}/><Field label="Company" name="company_name" defaultValue={item?.company_name} required/><Field label="Chinese company name" name="chinese_name" defaultValue={item?.chinese_name||""}/><SelectField label="Type" name="partner_type" value={item?.partner_type} options={partnerTypes}/><SelectField label="Status" name="status" value={item?.status} options={partnerStatuses}/><Field label="Location" name="location" defaultValue={item?.location||""}/><Field label="Website" name="website" type="url" defaultValue={item?.website||""}/><Field label="Contact person" name="contact_person" defaultValue={item?.contact_person||""}/><Field label="Role" name="contact_role" defaultValue={item?.contact_role||""}/><Field label="WeChat" name="wechat" defaultValue={item?.wechat||""}/><Field label="Email" name="email" type="email" defaultValue={item?.email||""}/><Field label="Phone" name="phone" defaultValue={item?.phone||""}/><Field label="English ability" name="english_ability" defaultValue={item?.english_ability||""}/><Field label="Interest level" name="interest_level" defaultValue={item?.interest_level||""}/><Field label="Last contact" name="last_contact" type="date" defaultValue={item?.last_contact||""}/><Textarea label="Client-visible notes" name="notes" defaultValue={item?.notes||""} rows={3}/><Textarea label="Source" name="source" defaultValue={item?.source||""} rows={3}/><div className="md:col-span-2"><Textarea label="Internal notes — admin only" name="internal_notes" defaultValue={item?.partner_internal_notes?.[0]?.content||""} rows={3}/></div><Submit/></form>}
export default async function AdminPartnersPage({searchParams}:{searchParams:Promise<{organization?:string}>}){const{organization}=await searchParams;const organizations=await getOrganizations();const items=await getAdminRecords<AdminPartner>("partners",organization,"*,organizations(name),partner_internal_notes(content)");return <><PageHeader eyebrow="PARTNERS" title="Move relationships forward." description="Research, qualify, contact, and maintain commercial context without turning the desk into a CRM."/><AdminClientFilter organizations={organizations} active={organization} basePath="/admin/partners"/><details className="mb-14"><summary className="cursor-pointer border-b border-ink/25 pb-1 text-sm">Add partner →</summary><PartnerForm organizations={organizations}/></details>{items.map(item=>{const org=Array.isArray(item.organizations)?item.organizations[0]:item.organizations;return <details key={item.id} className="border-t border-line py-7"><summary className="cursor-pointer list-none"><div className="grid gap-3 md:grid-cols-12"><div className="md:col-span-5"><h2 className="text-xl font-medium">{item.company_name}</h2><p className="mt-2 text-xs text-stone">{org?.name} · {item.partner_type} · {item.location}</p></div><p className="text-sm text-stone md:col-span-4">{item.contact_person||"No contact"}</p><div className="md:col-span-3"><Status>{item.status}</Status></div></div></summary><PartnerForm organizations={organizations} item={item}/><form action={deletePartner}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="organization_id" value={item.organization_id}/><button className="text-xs text-accent">Delete partner</button></form></details>})}</>}
