import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { classifySource } from "@/lib/meridian-intelligence/retrieval";
import { getSearchProvider } from "./provider";
import { rankSearchResults, sourceAwareQuery } from "./ranking";
import type { SearchQueryPlan } from "./types";

export class MeridianSearchRunner{
  async run(input:{organizationId:string;productId:string;queryPlanId:string}){
    const admin=createAdminClient();const {data:plan,error}=await admin.from("query_plans").select("id,organization_id,product_id,intent,query,query_language,preferred_source_types,product_terms,rationale,priority").eq("id",input.queryPlanId).eq("organization_id",input.organizationId).eq("product_id",input.productId).single();if(error||!plan)throw new Error("Query plan not found for this product and organization.");
    const typedPlan=plan as SearchQueryPlan;const executedQuery=sourceAwareQuery(typedPlan);const provider=getSearchProvider();const started=Date.now();
    const {data:run,error:runError}=await admin.from("search_runs").insert({organization_id:input.organizationId,product_id:input.productId,query_plan_id:input.queryPlanId,provider:provider.name,query:executedQuery,status:"RUNNING",metadata:{planned_query:typedPlan.query,intent:typedPlan.intent,rationale:typedPlan.rationale}}).select("id").single();if(runError||!run)throw new Error(runError?.message||"Search run could not be created.");const {data:progress}=await admin.from("analysis_progress").insert({organization_id:input.organizationId,product_id:input.productId,search_run_id:run.id,stage:"SEARCHING",status:"RUNNING",completed_stages:["PRODUCT_PROFILE","QUERY_PLANNING"]}).select("id").single();
    await admin.from("query_plans").update({status:"RUNNING"}).eq("id",typedPlan.id);
    await admin.from("retrieval_logs").insert({organization_id:input.organizationId,product_id:input.productId,query_plan_id:input.queryPlanId,event_type:"SEARCH_STARTED",message:executedQuery,metadata:{provider:provider.name}});
    try{
      const providerResults=await provider.search(executedQuery,{count:12,country:"CN",searchLanguage:typedPlan.query_language.startsWith("zh")?"zh-hans":"en"});const ranked=rankSearchResults(typedPlan,providerResults);
      const rows=[];for(const result of ranked){const classification=classifySource(result.url);const {data:source,error:sourceError}=await admin.from("source_registry").upsert({organization_id:input.organizationId,name:result.domain,domain:result.domain,source_type:result.sourceType,language:typedPlan.query_language,authority_level:result.sourceAuthority,regulatory_authority:classification.regulatoryAuthority,commercial_signal_strength:classification.commercialSignalStrength,access_method:"SEARCH_RESULT",status:classification.status},{onConflict:"organization_id,domain"}).select("id").single();if(sourceError)throw new Error(sourceError.message);rows.push({search_run_id:run.id,query_plan_id:typedPlan.id,product_id:typedPlan.product_id,organization_id:typedPlan.organization_id,source_id:source?.id||null,title:result.title,url:result.url,domain:result.domain,snippet:result.snippet,source_type:result.sourceType,source_authority:result.sourceAuthority,provider:result.provider,provider_rank:result.rank,meridian_rank:result.meridianRank,meridian_score:result.meridianScore,search_quality_score:result.meridianScore,score_breakdown:result.scoreBreakdown,eligible_for_client:result.eligibleForClient,duplicate_group_key:result.duplicateGroupKey,independent_source_key:result.independentSourceKey,ranking_reasons:result.rankingReasons,published_at:result.publishedAt,metadata:result.metadata});}
      if(rows.length){const {error:resultError}=await admin.from("search_results").upsert(rows,{onConflict:"query_plan_id,url"});if(resultError)throw new Error(resultError.message);}if(progress)await admin.from("analysis_progress").update({stage:"EVIDENCE_REVIEW",status:"QUEUED",completed_stages:["PRODUCT_PROFILE","QUERY_PLANNING","SEARCHING"]}).eq("id",progress.id);
      const completed=new Date().toISOString();const official=ranked.filter((item)=>item.sourceType==="AUTHORITATIVE").length;await admin.from("search_runs").update({status:"COMPLETE",completed_at:completed,result_count:ranked.length,official_source_count:official,duration_ms:Date.now()-started}).eq("id",run.id);await admin.from("query_plans").update({status:"COMPLETE"}).eq("id",typedPlan.id);await admin.from("retrieval_logs").insert({organization_id:input.organizationId,product_id:input.productId,query_plan_id:input.queryPlanId,event_type:"SEARCH_COMPLETED",message:`${ranked.length} candidates · ${official} official sources`,metadata:{provider:provider.name,duration_ms:Date.now()-started,result_count:ranked.length,official_source_count:official,search_run_id:run.id}});return{runId:run.id,results:ranked};
    }catch(error){const message=error instanceof Error?error.message:"Search failed.";if(progress)await admin.from("analysis_progress").update({stage:"FAILED",status:"FAILED",error_message:message}).eq("id",progress.id);await admin.from("search_runs").update({status:"FAILED",completed_at:new Date().toISOString(),failure_count:1,duration_ms:Date.now()-started,error_type:error instanceof DOMException&&error.name==="AbortError"?"TIMEOUT":"PROVIDER_ERROR",error_message:message}).eq("id",run.id);await admin.from("query_plans").update({status:"FAILED"}).eq("id",typedPlan.id);await admin.from("retrieval_logs").insert({organization_id:input.organizationId,product_id:input.productId,query_plan_id:input.queryPlanId,event_type:"SEARCH_FAILED",status:"FAILED",message,metadata:{provider:provider.name,duration_ms:Date.now()-started,search_run_id:run.id}});throw error;}
  }
}
