import Link from "next/link";
import { PageHeader, formatDate } from "@/components/china-desk-app/ui";
import { requireWorkspace } from "@/lib/china-desk/auth";
import { getMarketUpdates, getOverview } from "@/lib/china-desk/data";
import { createClient } from "@/lib/supabase/server";

export default async function OverviewPage() {
  const context = await requireWorkspace();
  const organizationId = context.organization!.id;
  const supabase=await createClient();
  const [{ metrics, activity }, updates, attentionResult] = await Promise.all([getOverview(organizationId), getMarketUpdates(organizationId),supabase.from("conflict_records").select("id,conflict_type,stronger_evidence_summary,relevance_score,confidence_score,suggested_action,created_at").eq("organization_id",organizationId).gte("relevance_score",60).eq("status","OPEN").order("relevance_score",{ascending:false}).limit(5)]);
  const attention=attentionResult.data||[];
  const firstName = context.profile.first_name || "there";
  const cards = [
    ["MARKET SIGNALS", metrics.market, "relevant developments", "/meridian/app/market"],
    ["TOP COMPETITORS", metrics.competitors, `${metrics.competitorUpdates} updated this month`, "/meridian/app/competitors"],
    ["OPPORTUNITIES", metrics.opportunities, "customers, distributors and partners", "/meridian/app/partners"],
    ["PRIORITY OPPORTUNITIES", metrics.priorityOpportunities, "qualified or actively progressing", "/meridian/app/partners?view=pipeline"],
    ["OPEN ACTIONS", metrics.requestsOpen, "research or verification requests", "/meridian/app/requests"],
  ] as const;
  return <><PageHeader eyebrow="MERIDIAN · CHINA OPPORTUNITY MAP" title={context.organization!.name} description={`Good morning, ${firstName}. What opportunities exist for you in China right now?`} action={<Link href="/meridian/app/ask" className="group inline-flex items-center gap-3 text-sm font-medium"><span className="border-b border-ink/25 pb-1">Ask Meridian</span><span className="text-accent transition-transform group-hover:translate-x-1">→</span></Link>} />
    {context.organization?.source_analysis_id && metrics.opportunities===0 ? <section className="mb-8 rounded-[20px] border border-accent/30 bg-accent/[0.08] p-6 sm:p-8"><p className="eyebrow text-accent">MERIDIAN IS BUILDING YOUR OPPORTUNITY MAP</p><h2 className="mt-4 text-3xl font-medium tracking-[-0.05em]">Your free snapshot is now your workspace context.</h2><p className="mt-4 max-w-3xl leading-7 text-charcoal">The product, objectives, buyer hypotheses, Chinese search strategy, risks and recommended actions are saved. Verified companies and signals will appear as discovery work is completed.</p><div className="mt-6 flex flex-wrap gap-6 text-sm"><Link href="/meridian/app/knowledge" className="text-accent">View saved context →</Link><Link href="/meridian/app/partners" className="text-charcoal hover:text-ink">Open opportunity map →</Link></div></section>:null}
    <div className="grid overflow-hidden rounded-2xl border border-line bg-elevated sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label,value,detail,href])=><Link key={label} href={href} className="border-b border-line p-6 transition-colors hover:bg-white/[0.025] sm:border-r lg:border-b-0 lg:last:border-r-0"><p className="eyebrow text-stone">{label}</p><p className="mt-6 text-4xl font-medium tracking-[-0.065em]">{value}</p><p className="mt-3 text-xs text-stone">{detail}</p></Link>)}</div>
    <section className="mt-20 border-t border-line pt-8"><p className="eyebrow text-accent">WORTH YOUR ATTENTION</p><h2 className="mt-4 max-w-2xl text-4xl font-medium tracking-[-0.055em]">Signals outside the obvious brief.</h2>{attention.length?<div className="mt-8 border-t border-line">{attention.map((item)=><article key={item.id} className="grid gap-4 border-b border-line py-6 md:grid-cols-12"><div className="md:col-span-3"><p className="text-sm font-medium">{item.conflict_type.replaceAll("_"," ")}</p><p className="mt-2 text-xs text-accent">Relevance {item.relevance_score}/100</p></div><p className="text-sm leading-6 text-charcoal md:col-span-6">{item.stronger_evidence_summary||"Conflicting evidence requires review."}</p><p className="text-xs leading-5 text-stone md:col-span-3">{item.suggested_action||"Review the underlying evidence."}</p></article>)}</div>:<p className="mt-6 text-sm text-stone">Nothing outside your brief has crossed Meridian’s 60-point relevance threshold.</p>}</section>
    <div className="mt-20 grid gap-16 xl:grid-cols-12"><section className="xl:col-span-8"><div className="flex justify-between border-b border-line pb-5"><h2 className="text-2xl font-medium tracking-[-0.04em]">Latest market signals</h2><Link href="/meridian/app/market" className="text-xs text-stone">View all →</Link></div>{updates.slice(0,3).map(update=><article key={update.id} className="border-b border-line py-6"><p className="eyebrow text-accent">{update.category}</p><h3 className="mt-3 text-xl font-medium tracking-[-0.035em]">{update.title}</h3><p className="mt-3 text-sm leading-6 text-stone">{update.summary}</p></article>)}</section>
    <section className="xl:col-span-3 xl:col-start-10"><h2 className="border-b border-line pb-5 text-lg font-medium">Recent activity</h2>{activity.length ? activity.map(item=><article key={item.id} className="border-b border-line py-5"><p className="text-sm">{item.action}</p><p className="mt-2 text-xs text-stone">{formatDate(item.created_at)}</p></article>) : <p className="py-8 text-sm text-stone">Activity will appear as your desk moves.</p>}</section></div></>;
}
