"use client";

import { useActionState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { resendVerification, signUp, type SignupState } from "@/app/desk/signup/actions";

const initial:SignupState={message:""};
const field="mt-3 w-full bg-transparent text-xl outline-none placeholder:text-stone/40";
export function SignupForm({website}:{website:string}){const router=useRouter();const [state,action,pending]=useActionState(signUp,initial);const [resendState,resendAction,resending]=useActionState(resendVerification,initial);useEffect(()=>{if(state.destination)router.push(state.destination);},[router,state.destination]);
  if(state.awaitingVerification&&state.email)return <section className="mt-12 bubble-card p-6 sm:p-8" aria-live="polite"><p className="eyebrow text-jade">CHECK YOUR EMAIL</p><p className="mt-5 text-sm text-charcoal">We sent a verification link to:</p><p className="mt-2 text-lg text-ink">{state.email}</p><p className="mt-5 text-sm leading-6 text-charcoal">Open the link to verify your email. Meridian will create your private CLIENT workspace and return you to onboarding.</p><form action={resendAction} className="mt-7"><input type="hidden" name="email" value={state.email}/><input type="hidden" name="website" value={website}/><button disabled={resending} className="min-h-11 text-sm font-medium text-accent disabled:opacity-50">{resending?"Sending…":"Resend verification email →"}</button></form>{resendState.message?<p className={`mt-4 text-sm ${resendState.success?"text-jade":"text-signal-red"}`} role={resendState.success?"status":"alert"}>{resendState.message}</p>:null}<a href="/meridian/login" className="mt-5 inline-block text-sm text-charcoal hover:text-ink">Back to sign in</a></section>;
  return <form action={action} className="mt-12 space-y-7"><input type="hidden" name="website" value={website}/>{[["Email","email","email","email"],["Password","password","password","new-password"],["Confirm password","confirm_password","password","new-password"]].map(([label,name,type,autoComplete])=><label key={name} className="block border-b border-ink/20 pb-3"><span className="eyebrow text-stone">{label}</span><input name={name} type={type} required minLength={type==="password"?10:undefined} autoComplete={autoComplete} className={field}/></label>)}<p className="text-xs text-charcoal">Use at least 10 characters.</p>{state.message?<p className={`rounded-xl border p-4 text-sm leading-6 ${state.success?"border-jade/30 bg-jade/[0.07] text-jade":"border-signal-red/30 bg-signal-red/[0.07] text-ink"}`} role={state.success?"status":"alert"}>{state.message}</p>:null}<button disabled={pending} className="min-h-12 w-full rounded-xl bg-accent px-5 py-3.5 text-sm font-semibold text-[#071018] disabled:opacity-50">{pending?"Creating your private workspace…":"Create Meridian account →"}</button></form>;
}
