import { AdminClientFilter } from "@/components/china-desk-app/admin-client-filter";
import { SelectField, Submit, Textarea } from "@/components/china-desk-app/admin-fields";
import { PageHeader, Status, formatDate } from "@/components/china-desk-app/ui";
import { requestStatuses } from "@/lib/china-desk/constants";
import { type ClientRequest, getAdminRecords, getOrganizations } from "@/lib/china-desk/data";
import { updateRequest } from "../actions";

type AdminRequest=ClientRequest&{organization_id:string;organizations:{name:string}|{name:string}[]};
export default async function AdminRequestsPage({searchParams}:{searchParams:Promise<{organization?:string}>}){const{organization}=await searchParams;const organizations=await getOrganizations();const items=await getAdminRecords<AdminRequest>("requests",organization);return <><PageHeader eyebrow="REQUESTS" title="Work in motion." description="Review client needs, change status, and leave clear progress updates."/><AdminClientFilter organizations={organizations} active={organization} basePath="/admin/requests"/><div className="border-t border-line">{items.map(item=>{const org=Array.isArray(item.organizations)?item.organizations[0]:item.organizations;return <article key={item.id} className="grid gap-6 border-b border-line py-8 xl:grid-cols-12"><div className="xl:col-span-3"><Status>{item.status}</Status><p className="mt-3 text-xs text-stone">{org?.name} · {formatDate(item.created_at)}</p></div><div className="xl:col-span-5"><h2 className="text-2xl font-medium">{item.title}</h2><p className="mt-3 text-sm leading-6 text-stone">{item.description}</p></div><form action={updateRequest} className="space-y-5 xl:col-span-4"><input type="hidden" name="id" value={item.id}/><input type="hidden" name="organization_id" value={item.organization_id}/><SelectField label="Status" name="status" value={item.status} options={requestStatuses}/><Textarea label="Client update" name="message" rows={2} placeholder="What changed or happens next?"/><Submit>Update request</Submit></form></article>})}</div></>}
